// RODADA BROWSER — campos de julgamento das amostras novas.
// Decididos a mao, lendo cada documento preservado.
import { readFileSync, writeFileSync } from "node:fs";
const S = id => `data/samples/IT-SOURCE-SAMPLES/${id}/MANIFEST.json`;
const BROWSER = { ACCESS_INSTRUMENT: "BROWSER", VPN_COUNTRY: "IT", BROWSER_REQUIRED: "NO", JS_REQUIRED: "NO", INTERACTION_REQUIRED: "NO", LOGIN_REQUIRED: "NO", CAPTCHA_OBSERVED: "NO", WAF_OBSERVED: "NO" };

const J = {
  "IT-T7-002": {
    OWNER_ID: "IT-OWN-MASAF", OWNER_CANONICAL_NAME: "MASAF — Ministero dell'agricoltura, della sovranita alimentare e delle foreste",
    OWNER_KIND: "OFFICIAL_NATIONAL_AGENCY", TERRITORY: "T7",
    SOURCE_NAME: "Elenco nazionale delle O.P. e A.O.P. riconosciute (escluso ortofrutta)",
    SOURCE_TYPE: "OFFICIAL_ORGANIZATION_REGISTRY", SOURCE_ROLE: "DISCOVERY_IDENTITY",
    ACCESS_METHOD: "PUBLIC_DOWNLOAD — planilha ODS", ACCESS_INSTRUMENT: "BROWSER para achar a rota; bytes baixados por HTTP do mesmo IP italiano",
    ...BROWSER, BROWSER_REQUIRED: "NO — mas a ROTA so foi encontrada navegando o menu Politiche nazionali > Filiere; adivinhar URL nao funcionou",
    ROTA_NAVEGADA: "masaf.gov.it > Politiche nazionali > Filiere > Organizzazioni di Produttori e loro Unioni > Elenco nazionale (IDPagina/6063) > anexo .ods",
    CANONICAL_URL: "https://www.masaf.gov.it/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/6063",
    SOURCE_DATE: "situacao em 31 dicembre 2025, arquivo atualizado em 08.04.2026",
    ORIGINAL_TITLE: "Elenco nazionale OP e AOP riconosciute al 31 dicembre 2025 - aggiornato al 08.04.2026",
    ORIGINAL_LANGUAGE: "it", SOURCE_LOCATION: "Roma — MASAF", FACT_LOCATION: "Italia inteira; cada linha traz a REGIONE e a SEDE (comune + provincia) da organizacao",
    EVIDENCE_CLASS: "OFFICIAL_ORGANIZATION_REGISTRY — nao e sinal de campo",
    CROP: "por setor: azeite/azeitona, cereais, vinho, leite, carnes, tabaco, batata, arroz, sementes, flores, apicultura",
    TOPICS: "reconhecimento oficial, forma societaria, sede, data de reconhecimento, provvedimento regionale, valor da producao comercializada (VPC)",
    GEOGRAPHIC_GRANULARITY: "ORGANIZACAO — com regiao e comune de sede",
    conteudo_medido: {
      linhas_de_tabela: 324, organizacoes_com_codigo: 269, OP: 261, AOP: 8,
      colunas: "CODICE IT, OP/AOP, SETTORE, DENOMINAZIONE, FORMA SOCIETARIA, P.IVA/C.F., SEDE, DATA DI RICONOSCIMENTO, PROVVEDIMENTO REGIONALE, DATA DI MANTENIMENTO, VPC anno 2023, VPC anno 2024, REGIONE",
      maiores_setores: { "Olio di oliva e olive da tavola (somando as variantes de rotulo)": 103, "Latte e derivados (todas as variantes)": 59, "Vitivinicolo": 16, "Cereali": 15, "Carni bovine": 13, "Pataticolo": 21 },
      maiores_regioes: { PUGLIA: 62, "EMILIA ROMAGNA": 27, CALABRIA: 22, CAMPANIA: 22, VENETO: 21, SICILIA: 18, SARDEGNA: 16 },
      sujeira_encontrada: "3 linhas com REGIONE = 'N.D.' e 1 linha em que o campo regiao traz 'D.D. n. 0053472' — erro de preenchimento na origem. NAO corrigimos o arquivo; fica registrado."
    },
    WHAT_IT_PROVES: "quem sao, oficialmente, as organizacoes de produtores reconhecidas na Italia fora do setor hortifruti: nome, forma juridica, setor, sede, regiao, data de reconhecimento e valor da producao comercializada declarado",
    WHAT_IT_DOES_NOT_PROVE: "nada de campo · nenhuma praga · nenhum preco de transacao · nao prova que a organizacao publica boletim · VPC e valor declarado de producao comercializada, NAO e venda de insumo nem market share",
    UPDATE_FREQUENCY: "ANNUAL — a mesma pagina lista as edicoes ao 31/12/2023, ao 31/12/2024 (REV.3) e ao 31/12/2025. Tres edicoes anuais visiveis.",
    HISTORICAL_DEPTH: "tres anos visiveis na pagina (2023, 2024, 2025)",
    AUTOMATION_FEASIBILITY: "MEDIUM — a pagina e estavel (IDPagina/6063), mas o link do anexo tem hash opaco que muda a cada nova edicao; e preciso varrer a pagina, nao adivinhar a URL",
    VERDICT: "GREEN", PRIORITY: "P0",
    por_que: "registro oficial real, preservado com hash, estruturado em planilha, com recorrencia anual provada por tres edicoes na mesma pagina",
    DECISAO_ADAMA: ["MARKET_DEVELOPMENT", "COMMERCIAL", "TECHNICAL"],
    pergunta_da_missao: "A ADAMA passa a ter a lista nominal de quem organiza os produtores italianos, por setor e por regiao — e descobre que 103 das 269 sao de azeite e 62 estao na Puglia. E o mapa de com quem falar, nao o que esta acontecendo no campo."
  },

  "IT-T3-011": {
    OWNER_ID: "IT-OWN-AGRIOS", OWNER_CANONICAL_NAME: "AGRIOS — Arbeitsgruppe fur den Integrierten Obstbau in Sudtirol / Gruppo di lavoro per la frutticoltura integrata in Alto Adige",
    OWNER_KIND: "TECHNICAL_NETWORK", TERRITORY: "T3",
    SOURCE_NAME: "Direttive per la frutticoltura integrata", SOURCE_TYPE: "DISCIPLINARE_TECNICO", ACCESS_METHOD: "PDF",
    ...BROWSER,
    CORRECAO_DE_DIAGNOSTICO: "a rodada anterior marcou AGRIOS como 'provavel JavaScript' porque o detector nao achou nenhum link. ERRADO. O site e em ALEMAO (Tirol do Sul) e o detector so procurava palavras italianas. Existe versao italiana em /it/. Nao havia bloqueio nenhum.",
    ROTA_NAVEGADA: "agrios.it > /it/ > Per i frutticoltori > Documenti e direttive > Direttive 2026",
    CANONICAL_URL: "https://www.agrios.it/it/per-i-frutticoltori/documenti-e-disciplinari/",
    SOURCE_DATE: "2026 (declarado no titulo e na capa)", ORIGINAL_TITLE: "DIRETTIVE PER LA FRUTTICOLTURA INTEGRATA 2026",
    ORIGINAL_LANGUAGE: "it (o mesmo documento existe em de)",
    SOURCE_LOCATION: "Terlano (BZ), Alto Adige", FACT_LOCATION: "Alto Adige / Sudtirol — area de aplicacao da diretriz",
    EVIDENCE_CLASS: "TECHNICAL_GUIDELINE",
    aviso_de_classe: "NAO e CURRENT_FIELD_SIGNAL e NAO e DEROGA. E a regra da temporada, nao a medicao do campo. Nao misturar.",
    CROP: "pomacee (maca e pera) — frutticoltura integrata", ISSUE: "difesa integrata, produtos permitidos e restricoes",
    TOPICS: "produzione integrata, prodotti fitosanitari admitidos, concimi, autocontrollo",
    outras_rotas_vistas: "Quaderno di campagna (.xlsx), Giacenza fitofarmaci (.xlsx), Check list autocontrollo (.xlsx), Requisiti concimi 2026 (.pdf), Accordo quadro BIO",
    WHAT_IT_PROVES: "que existe um disciplinar tecnico anual, publico e em italiano, que define o que pode ser usado na fruticultura integrada do Alto Adige em 2026",
    WHAT_IT_DOES_NOT_PROVE: "ocorrencia de praga · tratamento realizado · venda · quantos produtores seguem · autorizacao regulatoria (isso e do Ministero)",
    UPDATE_FREQUENCY: "ANNUAL — o titulo carrega o ano. NAO PROVADO por captura repetida: so a edicao 2026 foi vista nesta rota.",
    AUTOMATION_FEASIBILITY: "MEDIUM — PDF em WordPress, caminho estavel, mas o nome do arquivo e livre e muda a cada ano",
    VERDICT: "GREEN", PRIORITY: "P1",
    por_que: "documento tecnico real de 2026 preservado com hash, aberto, em italiano. P1 e nao P0 porque e regra anual, nao sensor: nao muda toda semana.",
    DECISAO_ADAMA: ["REGULATORY", "TECHNICAL", "COMMERCIAL"],
    pergunta_da_missao: "A ADAMA passa a saber, antes da temporada, o que o disciplinar do Alto Adige permite e proibe na maca — o que decide se um produto entra ou nao naquele mercado, independente de estar autorizado no pais."
  },

  "IT-T2-002": {
    OWNER_ID: "IT-OWN-ARPAV", OWNER_CANONICAL_NAME: "ARPAV — Agenzia Regionale per la Prevenzione e Protezione Ambientale del Veneto",
    OWNER_KIND: "OFFICIAL_REGIONAL_AGENCY", TERRITORY: "T2",
    SOURCE_NAME: "Bollettino Agrometeo...informa, por zona", SOURCE_TYPE: "BOLLETTINO_PERIODICO", ACCESS_METHOD: "PDF",
    ...BROWSER,
    BROWSER_REQUIRED: "NAO para baixar, SIM para descobrir: os 32 links de zona nao apareceram na leitura simples do HTML; so o navegador os revelou",
    ROTA_NAVEGADA: "arpa.veneto.it > Dati ambientali > Bollettini > Agrometeo > Agrometeo...informa > escolher a zona",
    ROTA: "https://www.arpa.veneto.it/risorse/data-agrometeo/agrometeo/32zone/agro_<NN>.pdf  (NN = 01..32)",
    SOURCE_DATE: "agro_01 gerado em 03/09/2026 16:09; agro_09 gerado em 02/09/2026 15:26 (data lida do proprio PDF)",
    ORIGINAL_TITLE: "Agrometeo...informa — bollettino di zona", ORIGINAL_LANGUAGE: "it",
    SOURCE_LOCATION: "Padova/Teolo — ARPAV", FACT_LOCATION: "zona agrometeorologica do Veneto correspondente ao numero do arquivo. DIFERENTE da sede.",
    EVIDENCE_CLASS: "AGROCLIMATIC_SIGNAL",
    LEI_DE_NAO_PROMOCAO: { regra: "AGROCLIMATIC_SIGNAL != PEST_OCCURRENCE", nota: "mesma lei aplicada a ARPAE (IT-T2-001)" },
    CROP: "n/a — agrometeorologia", TOPICS: "temperatura, chuva, zona agrometeorologica",
    GEOGRAPHIC_GRANULARITY: "ZONA — 32 zonas, agrupando comuni",
    LIMITE_DA_NOSSA_LEITURA: "o texto interno dos PDFs NAO saiu no nosso extrator (1 pagina, 12 imagens, 14 fontes — provavel layout grafico). Confirmamos: sao PDFs de verdade pelos bytes, sao arquivos DIFERENTES entre zonas (hashes distintos) e trazem data de geracao diferente por zona. O conteudo nao foi lido palavra por palavra.",
    WHAT_IT_PROVES: "que a ARPAV publica boletim agrometeorologico por zona, em PDF aberto, com 32 zonas e geracao independente por zona (datas diferentes entre agro_01 e agro_09)",
    WHAT_IT_DOES_NOT_PROVE: "o conteudo especifico de cada boletim (nao lido) · praga · risco modelado · decisao de tratamento",
    UPDATE_FREQUENCY: "a propria pagina DECLARA: zonas 2-15, 23, 24 atualizadas segunda e quinta no periodo primavera-verao e quarta no outono-inverno; zonas 1, 16, 20-33 em outro calendario. DECLARADO PELO SITE, nao medido por nos. UPDATE_FREQUENCY = NÃO SEI ate captura repetida.",
    HISTORICAL_DEPTH: "NENHUMA — o nome do arquivo nao tem data; cada zona tem UM arquivo que e sobrescrito. Quem nao coletar na hora, perde.",
    AUTOMATION_FEASIBILITY: "HIGH — 32 URLs fixas e previsiveis, sem login, sem JavaScript para baixar",
    VERDICT: "YELLOW", PRIORITY: "P1",
    por_que: "amostras reais preservadas e rota automatizavel, MAS o conteudo nao foi lido e nao ha arquivo historico. YELLOW por limitacao real, nao por duvida sobre a fonte.",
    DECISAO_ADAMA: ["TECHNICAL"],
    pergunta_da_missao: "A ADAMA ganha a leitura climatica do Veneto zona a zona — util para explicar pressao agronomica junto com um boletim fitossanitario. Sozinho nao decide nada."
  },

  "IT-T2-004": {
    OWNER_ID: "IT-OWN-SIAS", OWNER_CANONICAL_NAME: "SIAS — Servizio Informativo Agrometeorologico Siciliano (Regione Siciliana)",
    OWNER_KIND: "OFFICIAL_REGIONAL_AGENCY", TERRITORY: "T2",
    SOURCE_NAME: "SIAS — tabelas de consulta por grandeza meteorologica", SOURCE_TYPE: "TABELA_DE_DADOS", ACCESS_METHOD: "HTML",
    ...BROWSER,
    BROWSER_REQUIRED: "NAO para baixar a tabela, SIM para achar a rota: o site e um FRAMESET antigo e a leitura direta da home devolve casca vazia. Foi preciso descer nos frames.",
    ROTA_NAVEGADA: "sias.regione.sicilia.it > (frame) home.htm > Dati > Consultazione per grandezza > Precipitazioni giornaliere / T min giornaliera",
    CANONICAL_URL: "http://www.sias.regione.sicilia.it/NHEOWL0530_00.html",
    SOURCE_DATE: "janela 26/08/2026 a 05/09/2026 (11 dias) na tabela de chuva",
    ORIGINAL_TITLE: "Precipitazioni giornaliere (mm) — dal 26/08/2026 al 05/09/2026",
    ORIGINAL_LANGUAGE: "it", SOURCE_LOCATION: "Palermo — Regione Siciliana",
    FACT_LOCATION: "estacoes da Sicilia, agrupadas por provincia (ex.: Calatafimi, Castellammare del Golfo, Castelvetrano, Erice, Marsala, Mazara del Vallo, Pantelleria, Salemi)",
    EVIDENCE_CLASS: "AGROCLIMATIC_SIGNAL",
    LEI_DE_NAO_PROMOCAO: { regra: "AGROCLIMATIC_SIGNAL != PEST_OCCURRENCE" },
    CROP: "n/a", TOPICS: "chuva diaria, temperatura minima, ultimo dia chuvoso, chuva acumulada desde 1 de janeiro",
    GEOGRAPHIC_GRANULARITY: "ESTACAO — a rede declara 88 estacoes; a tabela agrupa por provincia",
    conteudo_medido: "tabela com valor por estacao e por dia, coluna 'Ultimo giorno piovoso' e coluna 'Precipitazioni cumulate dal 1 gen'. Horario declarado em UTC pelo proprio site.",
    WHAT_IT_PROVES: "que a Sicilia publica dado agrometeorologico diario por estacao, aberto, sem login, com janela movel de 11 dias e acumulado anual",
    WHAT_IT_DOES_NOT_PROVE: "praga · cultura · decisao de tratamento · dado por talhao · serie historica longa (a pagina so mostra a janela corrente)",
    UPDATE_FREQUENCY: "DAILY — a tabela e diaria e a janela termina 2 dias antes de hoje. Mas so uma captura foi feita: UPDATE_FREQUENCY = NÃO SEI ate a segunda.",
    HISTORICAL_DEPTH: "a pagina corrente cobre 11 dias. Existe 'SEZIONE RICHIESTA DATI' para serie historica — NAO testada nesta rodada.",
    AUTOMATION_FEASIBILITY: "HIGH — HTML estatico com URL fixa por grandeza, sem JavaScript, sem login. Atrito: charset antigo (iso-8859-1) e frameset na navegacao.",
    VERDICT: "GREEN", PRIORITY: "P1",
    por_que: "dado real por estacao preservado com hash, rota fixa e automatizavel. P1 porque e clima, nao sinal de praga — e a Sicilia ainda nao tem fonte fitossanitaria provada.",
    DECISAO_ADAMA: ["TECHNICAL"],
    pergunta_da_missao: "A ADAMA passa a ver a chuva e a temperatura da Sicilia estacao por estacao. Fecha metade da lacuna siciliana: o clima entra, o sinal de praga continua fora."
  },

  "IT-T3-008": {
    OWNER_ID: "IT-OWN-ARIF", OWNER_CANONICAL_NAME: "ARIF Puglia — Agenzia regionale per le attivita irrigue e forestali",
    OWNER_KIND: "OFFICIAL_REGIONAL_AGENCY", TERRITORY: "T3",
    SOURCE_NAME: "Notiziario Agrometeorologico & Fitosanitario Regionale (semanal) + Bollettino Meteorologico Regionale (diario)",
    SOURCE_TYPE: "BOLLETTINO_PERIODICO", ACCESS_METHOD: "PDF",
    ...BROWSER,
    ACHADO_PRINCIPAL: "o dominio do catalogo (arifpuglia.it) devolve 403 do CloudFront ATE no navegador italiano. Mas a ARIF publica — em OUTRO dominio: agrometeopuglia.it, que abre normalmente. E o caso classico de ROUTE_NOT_FOUND != SOURCE_BLOCKED. A rodada anterior teria condenado uma fonte viva.",
    OLD_ROUTE: "https://www.arifpuglia.it — DEAD (403 CloudFront, no curl E no navegador italiano)",
    CURRENT_ROUTE: "https://www.agrometeopuglia.it/bollettini — FOUND",
    ROTA: "https://www.agrometeopuglia.it/bollettino-elettronico/settimanale/<ANO>/Notiziario_Agrometeorologico_N<NN>_<DD-MM-AAAA>.pdf  ·  .../quotidiano/<ANO>/Giornaliero_Meteorologico_N<NN>_<DD-MM-AAAA>.pdf",
    SOURCE_DATE: "Notiziario n.36 de 02/09/2026 (valido ate 08/09) · n.35 de 26/08/2026 · Bollettino diario n.136 de 07/09/2026",
    ORIGINAL_TITLE: "Notiziario Agrometeorologico & Fitosanitario Regionale n. 36 del 02 settembre 2026 — Settimanale N.36 Anno XL",
    ORIGINAL_LANGUAGE: "it", SOURCE_LOCATION: "Bari — ARIF Puglia", FACT_LOCATION: "Puglia (regional)",
    EVIDENCE_CLASS: "MISTO — o titulo declara AGROMETEOROLOGICO & FITOSANITARIO. A parte agroclimatica e AGROCLIMATIC_SIGNAL; a parte fitossanitaria seria OBSERVED_FIELD_SIGNAL ou TECHNICAL_GUIDELINE, mas NAO foi lida (ver limite abaixo). Nao classificar a parte nao lida.",
    CROP: "NÃO SEI — a secao fitossanitaria nao foi lida", ISSUE: "NÃO SEI pelo mesmo motivo",
    TOPICS: "agrometeorologia regional, quadro sinotico, e uma secao fitossanitaria declarada no titulo",
    GEOGRAPHIC_GRANULARITY: "REGIONAL (a granularidade interna nao foi medida)",
    LIMITE_DA_NOSSA_LEITURA: "documento de 26 paginas, 55 imagens, 18 fontes. Nosso extrator simples leu as paginas iniciais (situacao meteorologica sinotica) e NAO conseguiu extrair a secao fitossanitaria. Buscas por 'oliv', 'mosca', 'soglia' no texto extraido deram ZERO. Isso NAO prova que a secao nao existe — prova que nao conseguimos ler. Fica registrado como limite do instrumento, nao como ausencia da fonte.",
    WHAT_IT_PROVES: "que a Puglia tem boletim regional semanal declaradamente agrometeorologico E fitossanitario, no ano XL (quadragesimo), em PDF aberto, com rota previsivel; e um boletim meteorologico diario de segunda a sexta",
    WHAT_IT_DOES_NOT_PROVE: "o conteudo fitossanitario especifico (nao lido) · cultura · praga · limiar · nenhuma ocorrencia de campo pode ser afirmada a partir desta amostra",
    UPDATE_FREQUENCY: "WEEKLY para o Notiziario — PROVADO pela listagem: N36 02/09, N35 26/08, N34 19/08, N33 12/08, N32 05/08, N31 29/07, N30 22/07, N29 15/07, N28 08/07, N27 01/07, N26 24/06. Espacamento de exatos 7 dias, saida as quartas, como o site declara. DAILY (seg-sex) para o Bollettino — declarado pelo site e coerente com a numeracao (n.136 em 07/09).",
    HISTORICAL_DEPTH: "o caminho tem o ano; 'Anno XL' no cabecalho sugere 40 anos de serie. Anos anteriores NAO testados.",
    AUTOMATION_FEASIBILITY: "HIGH — URL totalmente previsivel (numero + data no nome), sem login, sem JavaScript",
    VERDICT: "YELLOW", PRIORITY: "P0",
    por_que: "YELLOW, nao GREEN: a amostra esta preservada e a recorrencia semanal esta provada, mas a promessa que interessa — o sinal FITOSSANITARIO — nao foi verificada, porque nao conseguimos ler a secao. A REGRA 5 diz que amostra tem que provar o que a ficha promete. Prioridade P0 mesmo assim: e a Puglia, e a fonte tem tudo para virar GREEN assim que o PDF for lido com ferramenta melhor.",
    DECISAO_ADAMA: ["TECHNICAL", "MARKET_DEVELOPMENT"],
    PROXIMO_PASSO: "ler o PDF com extrator de PDF de verdade (poppler/pdftotext) e confirmar a secao fitossanitaria. Se ela trouxer cultura x praga x limiar, vira GREEN e provavelmente P0 absoluto."
  },

  "IT-T3-010": {
    OWNER_ID: "IT-OWN-012", OWNER_CANONICAL_NAME: "A.P.OL. — Associazione tra Produttori Olivicoli, Lecce (Societa Cooperativa)",
    OWNER_KIND: "PRODUCER_ORG", TERRITORY: "T3",
    SOURCE_NAME: "Bollettino fitosanitario Mosca dell'olivo", SOURCE_TYPE: "BOLLETTINO_PERIODICO", ACCESS_METHOD: "PDF",
    ...BROWSER,
    IDENTITY_RESOLVIDA: "o catalogo tinha URL = NÃO SEI. O site existe: www.apol.it — em HTTP, NAO em HTTPS. Foi por isso que o teste anterior com https:// devolveu zero. Mais um caso de ROUTE_NOT_FOUND != SOURCE_BLOCKED.",
    OLD_ROUTE: "https://www.apol.it — nao resolve", CURRENT_ROUTE: "http://www.apol.it — 200",
    ROTA: "http://www.apol.it/documenti/notizie/Bollettino_Mosca_dellOlivo_n_<N>_del_<DD_MM_AAAA>.pdf",
    SOURCE_DATE: "Bollettino n.9 valido de 07/09/2026 a 13/09/2026 (comeca HOJE) · n.8 de 31/08 a 06/09/2026",
    ORIGINAL_TITLE: "Bollettino n° 9 Mosca dell'olivo valido dal 07/09 al 13/09/2026",
    ORIGINAL_LANGUAGE: "it", SOURCE_LOCATION: "Lecce — sede da cooperativa",
    FACT_LOCATION: "COMPRENSORIO declarado dentro do documento. Na amostra n.9: 'BR - COLLINA LITORANEA', cobrindo BRINDISI, CAROVIGNO, CEGLIE MESSAPICA, CELLINO SAN MARCO, FASANO, FRANCAVILLA FONTANA, MESAGNE, ORIA, OSTUNI, SAN DONACI, SAN VITO DEI NORMANNI, TORCHIAROLO, TORRE SANTA SUSANNA, VILLA CASTELLI, SAN GIORGIO IONICO. DIFERENTE da sede (Lecce).",
    EVIDENCE_CLASS: "OBSERVED_FIELD_SIGNAL + COOPERATIVE_GUIDANCE",
    CROP: "OLIVE", ISSUE: "mosca dell'olivo (Bactrocera oleae)",
    TOPICS: "fase fenologica, catture em armadilha de feromonio, punture fertili, infestacao ativa, soglia di intervento, previsao diaria de 7 dias",
    GEOGRAPHIC_GRANULARITY: "COMPRENSORIO — agrupamento de comuni",
    conteudo_lido: "cabecalho 'MOSCA DELLE OLIVE 07/09/2026 - 13/09/2026'; comprensorio e lista de 15 comuni; fase fenologica 'INGROSSAMENTO FRUTTI'; valores 7 / 1 / 5% com rotulos STAZIONARIO e BASSO; sete datas diarias de 07 a 13/09; texto tecnico citando soglia di intervento, punture fertili, trappole a feromoni e queda de temperatura abaixo de 27-28 graus",
    WHAT_IT_PROVES: "que existe monitoramento semanal de mosca-da-azeitona na Puglia, por comprensorio, publicado aberto em PDF, com fase fenologica, contagem de capturas, percentual de infestacao e referencia explicita ao limiar de intervencao",
    WHAT_IT_DOES_NOT_PROVE: "tratamento realizado · venda · estoque · uso de produto · market share · numero por talhao individual · cobertura de toda a Puglia (a amostra cobre um comprensorio)",
    UPDATE_FREQUENCY: "WEEKLY — PROVADO na propria pagina: 9 boletins de 2026 (n.1 13/07 ate n.9 07/09) em intervalos de exatos 7 dias, mais 14 boletins de 2025. Duas temporadas visiveis.",
    HISTORICAL_DEPTH: "duas temporadas na mesma pagina: 2026 (9 edicoes) e 2025 (14 edicoes)",
    AUTOMATION_FEASIBILITY: "HIGH — URL previsivel com numero e data, sem login, sem JavaScript. Atrito unico: o site e HTTP, nao HTTPS.",
    VERDICT: "GREEN", PRIORITY: "P0",
    por_que: "e o perfil que o acervo inteiro so tinha na RAIF andaluza para uva: sinal de campo, por local, semanal, com limiar. Aqui e azeitona, na Puglia. Amostra preservada, recorrencia provada, rota automatizavel.",
    DECISAO_ADAMA: ["TECHNICAL", "MARKET_DEVELOPMENT", "COMMERCIAL"],
    pergunta_da_missao: "A ADAMA passa a saber, semana a semana e por comprensorio da Puglia, quando a mosca da azeitona cruza o limiar que manda tratar — na maior regiao olivicola da Italia. E o gatilho de decisao mais proximo do campo que esta rodada encontrou."
  },

  "IT-T5-002": {
    OWNER_ID: "IT-OWN-014", OWNER_CANONICAL_NAME: "Fondazione Edmund Mach — OpenPub (IRIS/CINECA)",
    OWNER_KIND: "RESEARCH_INSTITUTION", TERRITORY: "T5",
    SOURCE_NAME: "FEM OpenPub — repositorio institucional de publicacoes", SOURCE_TYPE: "REPOSITORIO_CIENTIFICO", ACCESS_METHOD: "HTML (plataforma IRIS)",
    ...BROWSER,
    CORRECAO_DE_ENDERECO: "o catalogo trazia publications.fmach.it, que nao resolve. O endereco vivo e openpub.fmach.it.",
    ROTA_NAVEGADA: "openpub.fmach.it > Ricerca > 'Drosophila suzukii' > registro do artigo",
    CANONICAL_URL: "https://openpub.fmach.it/handle/10449/91515",
    SOURCE_DATE: "2025-07-15", ORIGINAL_LANGUAGE: "en",
    ORIGINAL_TITLE: "Establishment and parasitism levels of Ganaspis kimorum on Drosophila suzukii in Northeastern Italy: insights from a 4-yr release program",
    autores: "Rossi Stacconi, M.V.; Fellin, L.; Grassi, A.; Colmagro, A.; Puppato, S.; Anfora, G.",
    SOURCE_LOCATION: "San Michele all'Adige (TN) — Fondazione Edmund Mach",
    FACT_LOCATION: "Nordeste da Italia — area do programa de soltura, conforme o proprio titulo",
    EVIDENCE_CLASS: "SCIENTIFIC_EVIDENCE",
    CROP: "fruit crops (pequenos frutos e cereja, pelo hospedeiro)", ISSUE: "Drosophila suzukii; controle biologico classico com Ganaspis kimorum",
    TOPICS: "parasitoide, controle biologico, resistencia a pesticida citada como motivacao, programa de soltura de 4 anos",
    conteudo_lido: "abstract completo publico, com tipologia '1.01 Articolo in rivista', autores e ano",
    volume_medido: "188 registros na busca por 'Drosophila suzukii'; 110 Settori Scientifico Disciplinari no catalogo; o site oferece 'esporta metadati'",
    WHAT_IT_PROVES: "que a FEM mantem repositorio publico, pesquisavel, com abstract aberto, autores, ano e tipologia — e que ha massa critica de ciencia italiana sobre pragas especificas",
    WHAT_IT_DOES_NOT_PROVE: "ocorrencia de campo hoje · eficacia comercial · autorizacao · venda · que o texto completo do artigo esteja aberto (so o registro e o abstract foram vistos)",
    UPDATE_FREQUENCY: "CONTINUO / IRREGULAR — repositorio alimentado a medida que sai publicacao. Nao medido.",
    HISTORICAL_DEPTH: "profunda — o repositorio cobre a producao da instituicao; nao medimos o alcance",
    AUTOMATION_FEASIBILITY: "MEDIUM — plataforma IRIS com URL de handle estavel e exportacao de metadados declarada. Atrito: a busca aceita parametros mas rejeitou uma combinacao nossa com HTTP 400; e preciso usar as rotas que a interface gera.",
    SOURCE_ROLE: "SCIENCE_SOURCE + IDENTITY_SOURCE (pesquisadores, para T6)",
    VERDICT: "GREEN", PRIORITY: "P1",
    por_que: "registro cientifico real preservado com hash, abstract aberto, autores e ano. P1 porque e ciencia: informa e calibra, nao dispara decisao semanal.",
    DECISAO_ADAMA: ["SCIENCE", "TECHNICAL"],
    pergunta_da_missao: "A ADAMA passa a acompanhar o que a ciencia italiana esta testando contra pragas especificas — inclusive alternativas nao quimicas, como o parasitoide deste artigo. Serve para antecipar para onde a recomendacao tecnica vai andar."
  }
};

for (const [id, extra] of Object.entries(J)) {
  const p = S(id);
  const m = JSON.parse(readFileSync(p, "utf8"));
  const out = { ...m, ...extra };
  for (const k of Object.keys(out)) if (String(out[k]).startsWith("PREENCHER_A_MAO")) delete out[k];
  writeFileSync(p, JSON.stringify(out, null, 1));
  console.log("ok", id.padEnd(11), "->", out.VERDICT, out.PRIORITY, "| RAW:", out.RAW_EVIDENCE_STATE);
}
