// Preenche os campos de JULGAMENTO dos manifestos da FASE D.
// Estes valores foram decididos a mao, olhando o conteudo de cada documento
// preservado. A maquina so escreve; quem julgou foi a leitura.
import { readFileSync, writeFileSync } from "node:fs";

const J = {
  "IT-T3-002": {
    OWNER_ID: "IT-OWN-CAMPANIA-SFR",
    OWNER_CANONICAL_NAME: "Regione Campania — Servizio Fitosanitario Regionale (UOD Fitosanitario)",
    OWNER_KIND: "OFFICIAL_REGIONAL_AGENCY",
    SOURCE_NAME: "Bollettini fitosanitari di produzione integrata — Campania, por provincia",
    TERRITORY: "T3",
    SOURCE_TYPE: "BOLLETTINO_PERIODICO",
    ACCESS_METHOD: "PDF",
    ROTA: "https://agricoltura.regione.campania.it/difesa/bollettini/bollettini_2026/pdf/<PROV>-<DD>-<MM>.pdf",
    SOURCE_DATE: "02-09-2026 (SA e NA) e 26-08-2026 (SA)",
    ORIGINAL_TITLE: "Bollettino fitosanitario — produzione integrata",
    SOURCE_LOCATION: "Napoli — sede da Regione Campania",
    FACT_LOCATION: "provincia do proprio boletim: Salerno (SA) e Napoli (NA). DIFERENTE da sede.",
    EVIDENCE_CLASS: "MISTO — predominante TECHNICAL_GUIDELINE (soglia, agronomico, chimico com substancia ativa) + OBSERVED_FIELD_SIGNAL pontual (o boletim marca 'Non Presente' / 'Presenza di' por avversita)",
    aviso_de_classe: "NAO tratar o bloco quimico como tratamento realizado. RECOMENDACAO != TRATAMENTO REALIZADO. O que e sinal de campo aqui e so o rotulo de presenca/ausencia.",
    CROP: "agrumi, drupacee, pomacee, olivo, ortive (varia por edicao e provincia)",
    ISSUE: "cimice asiatica (Halyomorpha halys), cocciniglia bianca, metcalfa, tristeza (CTV), gommosi/Phytophthora, afidi, monilia, Ceratitis capitata, corineo",
    TOPICS: "difesa integrata, soglia di intervento, fenologia, sostanza attiva",
    GEOGRAPHIC_GRANULARITY: "PROVINCIA — 5 provincias: AV, BN, CE, NA, SA",
    WHAT_IT_PROVES: "que existe orientacao fitossanitaria oficial semanal por provincia na Campania, com limiar de intervencao e substancia ativa nomeada, e com marcacao de presenca/ausencia de pragas observada pelo servico regional",
    WHAT_IT_DOES_NOT_PROVE: "tratamento efetivamente realizado no campo · venda · estoque · market share · produto ADAMA comprado · incidencia nacional · severidade numerica por ponto",
    UPDATE_FREQUENCY: "WEEKLY — PROVADO. A pagina do ano 2026 lista 14 edicoes de SA em intervalos de exatos 7 dias: 03-06, 10-06, 17-06, 24-06, 01-07, 08-07, 15-07, 22-07, 29-07, 05-08, 12-08, 19-08, 26-08, 02-09.",
    HISTORICAL_DEPTH: "o caminho tem o ano embutido (bollettini_2026); anos anteriores NAO foram testados nesta missao",
    AUTOMATION_FEASIBILITY: "HIGH — URL previsivel (<PROV>-<DD>-<MM>.pdf), sem JavaScript, sem login, sem captcha, PDF de verdade conferido nos bytes",
    SOURCE_ROLE: "FIELD_SIGNAL_SOURCE + TECHNICAL_GUIDANCE_SOURCE",
    VERDICT: "GREEN",
    por_que: "amostra real preservada com hash, recorrencia semanal provada na propria pagina, rota estavel e automatizavel, e o documento entrega cultura x praga x limiar x substancia ativa por provincia",
    PRIORITY: "P0",
    pergunta_da_missao: "Se o SINTONIA coletar isto toda semana, a ADAMA passa a ver, por provincia da Campania e em italiano oficial, qual praga o servico publico esta mandando tratar, com que limiar e com que substancia ativa — inclusive quando a substancia recomendada nao e a dela."
  },

  "IT-T10-002": {
    OWNER_ID: "IT-OWN-BMTI",
    OWNER_CANONICAL_NAME: "BMTI — Borsa Merci Telematica Italiana S.c.p.A.",
    OWNER_KIND: "TRADE_ASSOCIATION",
    SOURCE_NAME: "BMTI — prezzi e analisi di mercato",
    TERRITORY: "T10",
    SOURCE_TYPE: "ANALISE_DE_MERCADO",
    ACCESS_METHOD: "HTML",
    SOURCE_DATE: "24/08/2026 (cereais)",
    ORIGINAL_TITLE: "Mercato cerealicolo, mais e grano tenero in rialzo tra clima avverso e tensioni nel Mar Nero",
    SOURCE_LOCATION: "Roma — sede da BMTI",
    FACT_LOCATION: "Italia (listini das Borse Merci nacionais) + mercado internacional (Mar Negro, Europa). NAO e um ponto de campo.",
    EVIDENCE_CLASS: "MARKET_PRICE + analise narrativa",
    CROP: "mais, grano tenero, olio d'oliva",
    ISSUE: "variacao de preco, estresse hidrico, oferta",
    TOPICS: "prezzi, borse merci, export, produzione stimata",
    GEOGRAPHIC_GRANULARITY: "NACIONAL / PRACA DE BOLSA",
    WHAT_IT_PROVES: "que ha analise de preco datada e recorrente de milho, trigo mole e azeite, com variacao percentual mensal e comparacao anual, publicada aberta",
    WHAT_IT_DOES_NOT_PROVE: "preco de uma transacao especifica · volume vendido por empresa · sinal de campo · incidencia de praga · uso de defensivo",
    UPDATE_FREQUENCY: "NÃO SEI — ha datas diferentes no site, mas nao se mediu cadencia. Nao inferir de duas amostras.",
    AUTOMATION_FEASIBILITY: "MEDIUM — HTML publico e legivel por curl, mas a URL tem id numerico opaco (/46622/) e a listagem precisa ser percorrida",
    SOURCE_ROLE: "MARKET_SOURCE",
    VERDICT: "YELLOW",
    por_que: "amostra real preservada e conteudo de mercado de verdade, mas a recorrencia nao foi provada e a rota nao e previsivel. Falta medir a listagem e a cadencia.",
    PRIORITY: "P1",
    pergunta_da_missao: "Se o SINTONIA coletar isto, a ADAMA passa a ver o humor de preco de milho e trigo na Italia — util para explicar por que o produtor aperta ou solta o gasto com insumo, mas nao diz nada sobre praga."
  },

  "IT-T5-003": {
    OWNER_ID: "IT-OWN-AIPP",
    OWNER_CANONICAL_NAME: "AIPP — Associazione Italiana per la Protezione delle Piante (hospeda os PDFs) / Giornate Fitopatologiche",
    OWNER_KIND: "TRADE_ASSOCIATION",
    achado_de_owner: "os PDFs das Giornate Fitopatologiche moram em aipp.it, nao em giornatefitopatologiche.it. Sao DUAS organizacoes; nao fundir.",
    SOURCE_NAME: "Bilanci fitosanitari regionais 2024-2025 (ciclo 'I Giovedi dell'AIPP')",
    TERRITORY: "T5",
    SOURCE_TYPE: "APRESENTACAO_TECNICA",
    ACCESS_METHOD: "PDF",
    SOURCE_DATE: "27-11-2025 (sessao olivo)",
    ORIGINAL_TITLE: "Bilancio Fitosanitario Olivo 2024-2025 — Regione Basilicata / Regione Marche",
    SOURCE_LOCATION: "evento nacional online",
    FACT_LOCATION: "Basilicata e Marche — a regiao do balanco, DIFERENTE do local do evento",
    EVIDENCE_CLASS: "SCIENTIFIC_EVIDENCE / retrospectiva oficial de campanha — nao e sinal de campo corrente",
    CROP: "olivo (o ciclo cobre tambem vite e agrumi)",
    ISSUE: "balanco fitossanitario da campanha, por regiao",
    TOPICS: "avversita, andamento da campanha, rede de monitoramento",
    autores_e_instituicoes_visiveis: "Antonietta Altieri (Ufficio Fitosanitario Regione Basilicata); creditos a Servizi Difesa Integrata ALSIA, Servizio Agrometeorologico Lucano ALSIA, Laboratorio Fitopatologico ALSIA, Centro di saggio ALSIA, tecnicos de Organizzazioni di Produttori e consultores fitossanitarios",
    ganho_lateral: "esta amostra tambem alimenta T6 (pesquisadores) com nome + instituicao + regiao + cultura, e confirma o papel real da ALSIA na Basilicata",
    WHAT_IT_PROVES: "que existe uma retrospectiva anual, por regiao e por cultura, assinada pelos servicos fitossanitarios regionais, publicada em PDF aberto",
    WHAT_IT_DOES_NOT_PROVE: "situacao corrente do campo (e balanco de campanha passada) · venda · uso de produto · numero por talhao",
    UPDATE_FREQUENCY: "ANNUAL / EVENT_DRIVEN — declarado pelo proprio ciclo (2024-2025), nao medido por captura repetida",
    HISTORICAL_DEPTH: "os caminhos tem ano e mes (/2025/11/, /2025/12/) — sugere arquivo, NAO testado",
    AUTOMATION_FEASIBILITY: "MEDIUM — PDFs em WordPress com caminho datado e estavel, mas os nomes de arquivo sao livres; exige varrer a pagina do evento",
    SOURCE_ROLE: "SCIENCE_SOURCE + VALIDATION_SOURCE",
    VERDICT: "YELLOW",
    por_que: "duas amostras reais preservadas e conteudo excelente, mas e anual/por evento: nao serve de sensor corrente e a recorrencia nao foi medida por captura repetida",
    PRIORITY: "P1",
    pergunta_da_missao: "Se o SINTONIA coletar isto uma vez por ano, a ADAMA ganha o retrato oficial de como foi a campanha de cada praga em cada regiao — e o nome de quem assina. Serve para calibrar e para achar interlocutor, nao para reagir."
  },

  "IT-T2-001": {
    OWNER_ID: "IT-OWN-ARPAE",
    OWNER_CANONICAL_NAME: "ARPAE Emilia-Romagna",
    OWNER_KIND: "OFFICIAL_REGIONAL_AGENCY",
    SOURCE_NAME: "Bollettino agrometeorologico regionale — Emilia-Romagna",
    TERRITORY: "T2",
    SOURCE_TYPE: "BOLLETTINO_PERIODICO",
    ACCESS_METHOD: "PDF",
    ROTA: "https://www.arpae.it/.../bollettini-agrometeo/bollettini-<ANO>/<NN>_boll_agro_<AAAAMMDD>.pdf",
    CORRECAO_DE_ROTA: "a URL que o catalogo trazia (arpae.it/it/temi-ambientali/meteo/agrometeo) devolve HTTP 404. A rota viva foi encontrada a partir do portal de agricultura da Regiao.",
    ARMADILHA_EVITADA: "o site e Plone e oferece o link com sufixo /view, que devolve a CASCA HTML da pagina, nao o PDF. Baixamos sem o /view e conferimos a assinatura dos bytes: %PDF de verdade.",
    SOURCE_DATE: "31-08-2026 (boletim n. 35) e 24-08-2026 (n. 34)",
    ORIGINAL_TITLE: "Bollettino agrometeorologico n. 35 / n. 34 del 2026",
    SOURCE_LOCATION: "Bologna — sede da ARPAE",
    FACT_LOCATION: "Emilia-Romagna (regional). DIFERENTE da sede.",
    EVIDENCE_CLASS: "OBSERVED_FIELD_SIGNAL (agrometeorologia medida) — nao confundir com MODELLED_RISK",
    CROP: "n/a — e agrometeorologia, insumo para modelo de praga",
    TOPICS: "temperatura, chuva, agua no solo, andamento da campanha agraria",
    GEOGRAPHIC_GRANULARITY: "REGIONAL",
    WHAT_IT_PROVES: "que existe boletim agrometeorologico regional numerado e semanal, em PDF aberto, com arquivo por ano desde pelo menos 2021",
    WHAT_IT_DOES_NOT_PROVE: "presenca de praga · risco modelado · decisao de tratamento · dado por talhao",
    LIMITE_DA_NOSSA_LEITURA: "o texto interno do PDF nao saiu no nosso extrator simples (provavel PDF com muita imagem/fonte embutida). O arquivo esta preservado e integro; o conteudo nao foi lido palavra por palavra nesta missao.",
    UPDATE_FREQUENCY: "WEEKLY — PROVADO pela propria listagem: n.35=31/08, n.34=24/08, n.33=17/08, n.32=11/08, n.31=03/08, n.30=27/07, n.29=20/07. Numeracao sequencial + 7 dias.",
    HISTORICAL_DEPTH: "arquivos por ano visiveis de 2021 a 2026 — pelo menos 6 anos",
    AUTOMATION_FEASIBILITY: "HIGH — URL previsivel com numero e data, sem login, sem JavaScript. UNICA armadilha: nunca usar o sufixo /view.",
    SOURCE_ROLE: "FIELD_SIGNAL_SOURCE (clima)",
    VERDICT: "GREEN",
    por_que: "duas amostras reais preservadas com hash, PDF verificado nos bytes, recorrencia semanal provada pela listagem, profundidade historica de 6 anos e rota automatizavel",
    PRIORITY: "P0",
    pergunta_da_missao: "Se o SINTONIA coletar isto toda semana, a ADAMA ganha a base climatica da Emilia-Romagna — o que explica por que a praga apertou ou afrouxou. Sozinho nao diz nada de praga; casado com o boletim fitossanitario, diz muito."
  },

  "IT-T4-001": {
    OWNER_ID: "IT-OWN-MINSALUTE",
    OWNER_CANONICAL_NAME: "Ministero della Salute — Open Data",
    OWNER_KIND: "OFFICIAL_NATIONAL_AGENCY",
    SOURCE_NAME: "Dataset Prodotti Fitosanitari (registro de autorizacoes)",
    TERRITORY: "T4",
    SOURCE_TYPE: "REGISTRO_OFICIAL",
    ACCESS_METHOD: "CSV + XML + JSON, com dicionario de dados em PDF e RSS de aviso",
    SOURCE_DATE: "arquivo do dia 07-09-2026 (a data esta no nome: PROD_FTS_6_20260907)",
    ORIGINAL_TITLE: "Dataset Fitosanitari",
    SOURCE_LOCATION: "Roma",
    FACT_LOCATION: "ITALIA — abrangencia nacional",
    EVIDENCE_CLASS: "REGULATORY_AUTHORIZATION",
    CROP: "todas", ISSUE: "autorizacao de produto fitossanitario",
    TOPICS: "registro, titular, substancia ativa, formulacao, prazo de validade, indicacoes de perigo",
    conteudo_medido: "17.696 linhas; colunas incluem num_registrazione, denominazione_prodotto, ragione_sociale, data_registrazione, data_scadenza_autorizzazione, indicazioni_di_pericolo, sostanze_attive, codice/descrizione_formulazione",
    WHAT_IT_PROVES: "quais produtos estao formalmente autorizados na Italia, de quem sao, com que substancia ativa e ate quando vale a autorizacao",
    WHAT_IT_DOES_NOT_PROVE: "que o produto esta a venda · que foi usado · quanto foi vendido · market share · eficacia. AUTORIZADO != COMERCIALMENTE DISPONIVEL.",
    UPDATE_FREQUENCY: "o nome do arquivo carrega a data e hoje traz a data de hoje — indica atualizacao muito frequente, possivelmente diaria. NAO PROVADO: so uma data foi observada. UPDATE_FREQUENCY = NÃO SEI ate uma segunda captura.",
    AUTOMATION_FEASIBILITY: "HIGH — tres formatos estruturados, sem chave, sem login, com dicionario e com RSS de aviso de atualizacao",
    SOURCE_ROLE: "VALIDATION_SOURCE + IDENTITY_SOURCE",
    VERDICT: "GREEN",
    por_que: "dado estruturado real preservado com hash, 17.696 registros, dicionario oficial junto e rota sem atrito. O unico NÃO SEI que sobra e a cadencia.",
    PRIORITY: "P0",
    pergunta_da_missao: "Se o SINTONIA coletar isto, a ADAMA ve o tabuleiro regulatorio inteiro da Italia: o que ela tem autorizado, o que o concorrente tem, qual substancia esta vencendo autorizacao e quando. E a fonte que separa COMPANY_CLAIM de REGULATORY_FACT."
  },

  "IT-T1-001": {
    OWNER_ID: "IT-OWN-ISTAT",
    OWNER_CANONICAL_NAME: "ISTAT — Istituto Nazionale di Statistica",
    OWNER_KIND: "OFFICIAL_NATIONAL_AGENCY",
    SOURCE_NAME: "Coltivazioni — superfici e produzione, dado provincial (dataflow 101_1015_DF_DCSP_COLTIVAZIONI_2)",
    TERRITORY: "T1",
    SOURCE_TYPE: "SERIE_ESTATISTICA",
    ACCESS_METHOD: "API — SDMX 2.1 REST, documentada e sem chave",
    ROTA: "https://esploradati.istat.it/SDMXWS/rest/data/IT1,101_1015_DF_DCSP_COLTIVAZIONI_2,1.0/?startPeriod=&endPeriod=  com Accept: application/vnd.sdmx.data+csv",
    SOURCE_DATE: "consulta de 2025 em diante; o retorno ja traz linhas de 2026",
    SOURCE_LOCATION: "Roma", FACT_LOCATION: "todas as provincias italianas",
    EVIDENCE_CLASS: "SERIE_OFICIAL_DE_PRODUCAO (nem sinal de campo, nem preco)",
    CROP: "233 tipos de cultura distintos no arquivo preservado",
    TOPICS: "superficie, producao, provincia, ano",
    conteudo_medido: "77.363 linhas; colunas DATAFLOW, FREQ, REF_AREA, DATA_TYPE, TYPE_OF_CROP, TIME_PERIOD, OBS_VALUE, UNIT_MEAS",
    WHAT_IT_PROVES: "area e producao por cultura e por provincia, oficial, com serie temporal",
    WHAT_IT_DOES_NOT_PROVE: "praga · clima · preco · uso de defensivo · quem plantou · decisao de compra",
    UPDATE_FREQUENCY: "ANNUAL (declarado pela natureza da serie) — nao medido por captura repetida",
    AUTOMATION_FEASIBILITY: "HIGH pela API SDMX. ATENCAO: o portal visual esploradati.istat.it exige JavaScript e chegou a devolver erro de servidor — a API funciona, o site nao. Sao coisas diferentes.",
    SOURCE_ROLE: "MARKET_SOURCE / contexto de producao",
    VERDICT: "GREEN",
    por_que: "amostra real preservada com hash, rota SDMX oficial e estavel, granularidade provincial e 233 culturas. E a fonte que diz ONDE existe cultura o bastante para o resto importar.",
    PRIORITY: "P0",
    pergunta_da_missao: "Se o SINTONIA coletar isto, a ADAMA para de tratar 'Italia' como um lugar so: passa a saber em que provincia ha hectare de oliveira, de milho ou de trigo duro suficiente para uma acao valer a pena."
  }
};

for (const [id, extra] of Object.entries(J)) {
  const p = `data/samples/IT-SOURCE-SAMPLES/${id}/MANIFEST.json`;
  const m = JSON.parse(readFileSync(p, "utf8"));
  const out = { ...m, ...extra };
  // limpa os marcadores que nao foram preenchidos
  for (const k of Object.keys(out)) if (out[k] === "PREENCHER_A_MAO" || String(out[k]).startsWith("PREENCHER_A_MAO —")) delete out[k];
  writeFileSync(p, JSON.stringify(out, null, 1));
  console.log("ok", id, "->", out.VERDICT, out.PRIORITY, "| RAW:", out.RAW_EVIDENCE_STATE);
}
