    // ---- science · scientific intelligence -------------------------------
    /* §12 · This block used to be built on four fixtures: ITALY_SCIENCE (the
       authored SCIENCE→BUSINESS layer) plus the legacy fixture's SCI_THEMES
       (10 hand-written themes), RECORDS (36 rows, 24 of them generated by
       seed()) and INSTITUTIONS (12 hardcoded names). All four are gone.
       Nothing in this block reads the fixture any more. Everything reads
       AM.collections only: scienceThemes 5, scienceRecords 88, researchers 60,
       resistance 34, publicPeople 15, cropWindows 29 — measured, not assumed.

       What that costs on screen, stated up front so nobody reads it as a bug:
       themes 13 -> 5, institutions 12 -> 6, research rows 36 -> 88,
       researchers 14 -> 60, and every "business relevance" verdict is gone
       because no external source states one. */
    const sciT0 = (APP0 && APP0.scienceThemes) ? APP0.scienceThemes.records : [];
    const sciR0 = (APP0 && APP0.scienceRecords) ? APP0.scienceRecords.records : [];
    const sciP0 = (APP0 && APP0.researchers) ? APP0.researchers.records : [];
    const sciPP0 = (APP0 && APP0.publicPeople) ? APP0.publicPeople.records : [];
    const sciRes0 = (APP0 && APP0.resistance) ? APP0.resistance.records : [];
    const sciWin0 = (APP0 && APP0.cropWindows) ? APP0.cropWindows.records : [];
    const sciIT = s.lang === 'it';
    const sciL = (it, en) => (sciIT ? it : en);
    const sciUNK = sciL('non noto', 'not known');
    /* The narrative gate. A field that arrives { state, it, en } is only printed
       when upstream approved a localized text. NOT_APPROVED_FOR_DISPLAY means an
       internal Portuguese research note exists — it renders as nothing, never as
       n.it. Measured on this package: resistance MECHANISM is in that state on
       34/34 records, which is why no mode of action is published below. */
    const sciNar = (n) => (n && n.state === 'CLEAR') ? (sciIT ? (n.it || n.en) : (n.en || n.it)) : null;
    /* The ingested GIRE / OpenAlex fields carry the analyst's own working notes
       in Portuguese, inline with the fact. This is the note detector; anything
       it matches is dropped rather than shown. */
    const sciNOTE = /NAO SEI|N[ÃA]O SEI|n[ãa]o sei|a ficha|A ficha|literal:|sinonimi|sin[oó]nimo|ATENCAO|ATEN[ÇC][ÃA]O|o titulo|nao |n[ãa]o /;

    /* §12 · Display labels for the real SCREAMING_SNAKE tokens. T.CROPS and
       T.ISSUES are keyed on the demo's English labels and have an entry for not
       one of the tokens the ingested science actually uses, so without this map
       an Italian screen would print VINE and FLAVESCENCE in raw uppercase.
       These are labels for a query, not translations and not claims. */
    const sciCropL = (tok) => {
      const k = String(tok || '').toUpperCase();
      const canon = { VINE: 'Grapevine', DURUM_WHEAT: 'Durum Wheat', OLIVE: 'Olive', MAIZE: 'Maize', WHEAT: 'Wheat', RICE: 'Rice', SOYBEAN: 'Soybean', TOMATO: 'Tomato' }[k];
      if (canon) return cl(canon);
      /* CEREAL names a group, not a crop; the model deliberately refuses to
         resolve it and so does this label. */
      if (k === 'CEREAL') return sciL('cereali (gruppo)', 'cereals (group)');
      return k ? k.replace(/_/g, ' ').toLowerCase() : sciUNK;
    };
    const SCI_ISSUE_L = {
      FLAVESCENCE: ['Flavescenza dorata', 'Flavescence dorée'],
      FUSARIUM: ['Fusariosi della spiga', 'Fusarium head blight'],
      BACTROCERA: ['Mosca delle olive', 'Olive fruit fly'],
      BORER_DIABROTICA: ['Piralide e diabrotica', 'European corn borer and Diabrotica'],
      HERBICIDE_RESISTANCE: ['Resistenza agli erbicidi', 'Herbicide resistance'],
      REPILO: ['Occhio di pavone (repilo)', 'Peacock spot (repilo)'],
      DOWNY_MILDEW: ['Peronospora', 'Downy mildew'],
      SEPTORIA: ['Septoriosi', 'Septoria leaf blotch'],
    };
    const sciIssueL = (tok) => { const e = SCI_ISSUE_L[String(tok || '').toUpperCase()]; return e ? sciL(e[0], e[1]) : (tok ? String(tok).replace(/_/g, ' ').toLowerCase() : sciUNK); };
    /* The pest / disease / weed class is a FACT and comes from AM.categoryOf.
       The five theme tokens already carry it through the model's ui. The three
       issue tokens below appear only on records that match no theme (5 of 88),
       so their canonical class is named here once, explicitly, rather than
       guessed from a colour. */
    const SCI_ISSUE_TYPE = { FLAVESCENCE: 'PEST', FUSARIUM: 'DISEASE', BACTROCERA: 'PEST', BORER_DIABROTICA: 'PEST', HERBICIDE_RESISTANCE: 'WEED', REPILO: 'DISEASE', DOWNY_MILDEW: 'DISEASE', SEPTORIA: 'DISEASE' };
    const sciCat = (tok) => (AM ? AM.categoryOf(SCI_ISSUE_TYPE[String(tok || '').toUpperCase()] || null) : { color: '#8F8886', dark: '#3A3533', soft: '#B1A9A7', iconAsset: '', label: null });
    const SCI_MTYPE = {
      PEER_REVIEWED_PAPER: ['articolo con revisione paritaria', 'peer-reviewed paper'],
      PREPRINT: ['preprint', 'preprint'],
      OTHER_TECHNICAL_PUBLICATION: ['altra pubblicazione tecnica', 'other technical publication'],
    };
    const SCI_MROLE = {
      DISEASE_PEST_MONITORING: ['monitoraggio di malattie e insetti', 'disease and pest monitoring'],
      METHOD_MECHANISM: ['metodo o meccanismo', 'method or mechanism'],
      NEW_SCIENTIFIC_EVIDENCE: ['nuova evidenza scientifica', 'new scientific evidence'],
      MANAGEMENT_GUIDANCE: ['indicazioni di gestione', 'management guidance'],
      REVIEW_SYNTHESIS: ['rassegna / sintesi', 'review / synthesis'],
      EXPERIMENT_RESULT: ['risultato sperimentale', 'experiment result'],
    };
    const sciVocab = (map, k) => { const e = map[String(k || '').toUpperCase()]; return e ? sciL(e[0], e[1]) : (k ? String(k).replace(/_/g, ' ').toLowerCase() : ''); };
    const SCI_IDENT = {
      ORCID_PRESENT_NOT_RESOLVED_HERE: ['ORCID presente · non risolto qui', 'ORCID present · not resolved here'],
      NO_ORCID_IN_SOURCE: ['nessun ORCID nella fonte', 'no ORCID in source'],
    };

    /* §12 · The theme -> canonical crop window join. This is NAVIGATION: the
       theme is a bibliometric query and the window is an audited agronomic
       record; sharing a crop and a target is a reason to look, never a finding.
       The issue vocabularies genuinely differ (the theme says BACTROCERA, the
       window says "Olive Fruit Fly"), so the question is translated here, once,
       explicitly — exactly as the model translates the three opportunities.
       MEASURED matches: flavescence 2, fusarium 2, bactrocera 3, borer 6,
       herbicide resistance 0 (that theme has no crop at all, so it is never
       joined to a crop window). */
    const SCI_WIN_ISSUE = {
      FLAVESCENCE: ['Flavescenza Dorata'],
      FUSARIUM: ['Fusarium Head Blight'],
      BACTROCERA: ['Olive Fruit Fly'],
      BORER_DIABROTICA: ['European Corn Borer', 'Diabrotica Adults', 'Diabrotica Larvae'],
      HERBICIDE_RESISTANCE: [],
    };
    const sciWinStatusColor = { WINDOW_OPEN: '#009845', NEXT_CYCLE: '#00A0DF', WINDOW_CLOSED: '#8F8886', DATE_UNKNOWN: '#F5B317' };
    const sciWinsFor = (t) => {
      const iss = SCI_WIN_ISSUE[String(t.issueToken || '').toUpperCase()] || [];
      if (!t.cropCanonical || !iss.length) return [];
      /* Presentation sort only: the soonest supplied start first. It orders the
         list, it does not decide a state. */
      return sciWin0.filter((x) => x.crop === t.cropCanonical && iss.indexOf(x.issue) >= 0)
        .slice().sort((a, b) => (a.daysToStart === null ? 1e9 : a.daysToStart) - (b.daysToStart === null ? 1e9 : b.daysToStart));
    };

    const sciSTR = (AM && AM.STRENGTH) || {};
    const sciAbsence = (AM && AM.ABSENCE_RULE) || T.absenceRuleShort || '';
    const sciUniq = (a) => a.filter((v, i) => v && a.indexOf(v) === i);

    /* §12 · One theme card. Everything on it is either a verbatim upstream
       number (works / authors / record and researcher counts), a verbatim
       upstream verdict (window status, label verdict) or an explicit unknown.
       Nothing here is a business ranking: none is stated by any external
       source, so none is rendered — the badge, the "why", the owners, the
       actions and the connected-opportunity line are all empty by design. */
    const sciBuild = (t) => {
      const wins = sciWinsFor(t);
      const verified = sciUniq(wins.reduce((a, x) => a.concat(x.verifiedProducts || []), []));
      const notFound = sciUniq(wins.reduce((a, x) => a.concat(x.notFoundProducts || []), []));
      /* Rule 10 · never "ADAMA has no product". Three distinct states, and the
         third one is the honest answer when the label question was never asked
         for this theme because no canonical window matches it. */
      const pstate = verified.length ? 'VERIFIED_LABEL_MATCH'
        : (notFound.length ? 'NO_CONFIRMED_MATCH_CURRENT_READING' : 'LABEL_CHECK_NEEDED');
      const pLabel = { VERIFIED_LABEL_MATCH: sciL('CORRISPONDENZA VERIFICATA IN ETICHETTA', 'VERIFIED LABEL MATCH'),
        NO_CONFIRMED_MATCH_CURRENT_READING: sciL('NESSUNA CORRISPONDENZA CONFERMATA IN QUESTA LETTURA', 'NO CONFIRMED MATCH IN THIS READING'),
        LABEL_CHECK_NEEDED: sciL('VERIFICA ETICHETTA NECESSARIA', 'LABEL CHECK NEEDED') }[pstate];
      const statuses = sciUniq(wins.map((x) => x.status));
      const cat = (t.ui && t.ui.color) ? t.ui : sciCat(t.issueToken);
      return {
        id: t.id, key: t.id, title: t.title,
        crop: t.cropCanonical || t.cropToken, issue: t.issueToken,
        cropL: sciCropL(t.cropToken), issueL: sciIssueL(t.issueToken),
        /* Presentation metadata only (Rule 4): the class itself came from the
           canonical ISSUE_TYPE through AM.categoryOf. */
        category: Object.assign({}, cat, { icon: cat.iconAsset || '' }),
        /* The QUERY is the only honest definition of what WORKS counted, so it
           travels with every number derived from it. */
        note: t.query, query: t.query,
        works: t.works, hasWorks: t.works !== null && t.works !== undefined,
        worksLabel: (t.works === null || t.works === undefined) ? sciUNK : t.works + ' ' + sciL('lavori nella query', 'works in the query'),
        /* There is no trend, movement or growth field anywhere upstream: WORKS,
           AUTHORS_IT, AUTHORS_WITH_ORCID and AUTHORS_ACTIVE_SINCE_2024 are four
           point-in-time counts from ONE query, with no earlier headcount to
           compare against. So activity is not measured and is not substituted. */
        activity: sciL('NON MISURATA', 'NOT MEASURED'),
        sourceTrend: '',
        authorsIt: t.authorsIt, authorsWithOrcid: t.authorsWithOrcid, authorsActiveSince2024: t.authorsActiveSince2024,
        recordCount: t.recordCount, researcherCount: t.researcherCount,
        /* §12 · No external source ranks a research theme by business
           relevance, so the badge, the reasoning marks, the owners, the
           actions and the limits are empty rather than authored. The colours
           stay, because a card still needs a border. */
        rel: '', relColor: cat.color, relInk: cat.ink || '#fff', relBright: cat.soft || cat.color,
        relTint: 'transparent', relBorder: 'rgba(203,197,195,0.12)', relDef: '',
        short: t.query ? sciL('Query: ', 'Query: ') + t.query : '',
        why: [], changes: [], owners: [], ownersLabel: '', actions: [], limits: [],
        shows: '', notShows: '',
        isResistance: String(t.issueToken || '').toUpperCase() === 'HERBICIDE_RESISTANCE',
        isStrategic: false, isWeed: (cat.key === 'weed'),
        /* No mode-of-action exposure is derived: see the resistance block below
           for the measured reason (34/34 mechanisms arrive not approved). */
        hasMoa: false, moaGroups: [],
        moaNote: sciL(
          'il meccanismo dichiarato dalla fonte arriva come nota di ricerca non approvata alla pubblicazione su 34/34 casi; la sovrapposizione mostrata qui è di genere botanico, non di meccanismo.',
          'the mechanism the source states arrives as a research note not approved for display on 34/34 cases; the overlap shown here is botanical genus, not mechanism.'),
        products: verified.slice(0, 4).map((n) => ({ name: n, go: () => this.openProduct(n) })),
        productCount: verified.length,
        portfolioState: pLabel, portfolioStateKey: pstate,
        portfolioColor: (sciSTR[pstate] || {}).color || '#B1A9A7',
        absenceRule: pstate === 'NO_CONFIRMED_MATCH_CURRENT_READING' ? sciAbsence : '',
        /* Rule 7 · the state is upstream CURRENT_STATUS, restated verbatim
           through the shared status dictionary. No date comparison happens
           here and no ACT NOW is invented. */
        nextMoment: statuses.length ? statuses.map((k) => wst(k)).join(' · ') : sciL('NESSUNA FINESTRA COLLEGATA', 'NO LINKED WINDOW'),
        nextMomentMeta: wins.length
          ? sciUniq(wins.map((x) => x.issue)).join(' · ') + ' · ' + sciUniq(wins.map((x) => x.region)).join(', ')
          : sciL('nessuna finestra canonica per questo bersaglio — non si prende in prestito il conto alla rovescia di un altro',
            'no canonical window for this target — no countdown is borrowed from another one'),
        nextMomentColor: wins.length ? (sciWinStatusColor[wins[0].status] || '#8F8886') : '#8F8886',
        hasWindow: wins.length > 0, windowCount: wins.length,
        goWindow: () => wins.length && this.openWindow(wins[0].id),
        /* No market verdict, temperature or trajectory exists upstream — the
           model says so in as many words — so none is printed here. The link
           still goes to Market Pulse, which is navigation. */
        market: sciL('NESSUN VERDETTO DI MERCATO DERIVATO', 'NO MARKET VERDICT DERIVED'),
        marketColor: '#8F8886',
        goMarket: () => this.go({ view: 'market' }),
        /* The theme -> opportunity link existed only in the fixture's
           hand-written cases: [] arrays. Nothing upstream carries it. */
        caseCount: 0, caseObjs: [], opportunityLine: '',
        records: sciR0.filter((r) => r.themeKey === t.id).slice().sort((a, b) => String(b.publishedAt).localeCompare(String(a.publishedAt))).slice(0, 5)
          .map((r) => ({ id: r.id, descriptor: r.title, year: r.year || sciUNK, institution: r.institution, study: sciVocab(SCI_MTYPE, r.materialType) + ' · ' + sciVocab(SCI_MROLE, r.materialRole) })),
        people: [],
        impact: () => this.setState({ sciImpactId: t.id }),
        goTheme: () => this.openTheme(t.id),
        extra: false,
      };
    };

    const sciAll = sciT0.map(sciBuild);
    /* Navigation filter over the canonical pest / disease / weed class. It is
       a class, not a ranking: the previous eight-way SCIENCE→BUSINESS ladder
       (ACT NOW / PORTFOLIO RISK / ...) was authored in a fixture. */
    const sciCounts = sciUniq(sciAll.map((x) => x.category.key)).map((k) => {
      const one = sciAll.find((x) => x.category.key === k).category;
      /* The filter token is the canonical key in upper case, because the shared
         export prints s.sciFilter verbatim in the CLEAR FILTER chip and a
         localized label there would break the moment the language changes. */
      const tok = String(k).toUpperCase();
      const on = s.sciFilter === tok;
      return {
        label: L(one.label || k), n: sciAll.filter((x) => x.category.key === k).length,
        color: one.soft || one.color, def: sciL('classe canonica del bersaglio — non è una graduatoria commerciale', 'canonical target class — not a commercial ranking'),
        on, bg: on ? 'rgba(255,255,255,0.05)' : '#1C1817',
        border: on ? one.color : 'rgba(203,197,195,0.10)',
        go: () => this.setState({ sciFilter: on ? '' : tok }),
      };
    });
    const sciThemes = sciAll.filter((x) => !s.sciFilter || String(x.category.key).toUpperCase() === s.sciFilter);
    /* "MOST IMPORTANT FOR ADAMA NOW" ranked the fixture's business ladder.
       Nothing external ranks a research theme by importance to a company, so
       the strip is emptied rather than re-ranked by publication volume, which
       would read as the same claim with a different number under it. */
    const sciTop = [];
    /* STRATEGIC SCIENCE & PORTFOLIO GAPS: "strategic" was a fixture flag, and
       a portfolio gap per theme would be an absolute negative built out of a
       navigation join. Emptied. */
    const sciStrategic = [];
    const sciResistance = sciAll.filter((x) => x.isResistance);
    const sciWeed = sciAll.filter((x) => x.isWeed);
    const sciTotal = sciAll.length;
    const sciClear = () => this.setState({ sciFilter: '' });
    const sciImpact = sciAll.find((x) => x.id === s.sciImpactId) || null;
    const sciCloseImpact = () => this.setState({ sciImpactId: null });

    /* §12 · The one caption this screen cannot ship without. 88 is a real
       count and a misleading one on its own: MEASURED, the 88 records carry 7
       distinct AUTHOR values and 6 distinct first-author affiliations, two of
       which are not Italian. It is the publication list of seven researchers,
       not a survey of Italian science, and the numbers are recomputed here so
       the sentence cannot go stale. */
    const sciAuthorN = sciUniq(sciR0.map((r) => r.author)).length;
    const sciInstN = sciUniq(sciR0.map((r) => r.institution)).length;
    const sciYears = sciR0.map((r) => r.year).filter(Boolean).sort();
    const sciActivityNote = sciR0.length ? sciL(
      sciR0.length + ' record scientifici, ' + sciAuthorN + ' autori distinti e ' + sciInstN + ' affiliazioni distinte'
        + (sciYears.length ? ' (' + sciYears[0] + '–' + sciYears[sciYears.length - 1] + ')' : '')
        + '. È la lista di pubblicazioni di ' + sciAuthorN + ' ricercatori, non un censimento della scienza italiana. Il volume di lavori dei temi viene da un\'altra interrogazione e conta un universo diverso: un tema può avere ' + (sciT0[2] ? sciT0[2].works : 0) + ' lavori e 0 record in questa raccolta. L\'affiliazione è dell\'autore, non dello studio.',
      sciR0.length + ' science records, ' + sciAuthorN + ' distinct authors and ' + sciInstN + ' distinct affiliations'
        + (sciYears.length ? ' (' + sciYears[0] + '–' + sciYears[sciYears.length - 1] + ')' : '')
        + '. This is the publication list of ' + sciAuthorN + ' researchers, not a survey of Italian science. The theme works count comes from a different query over a different universe: a theme can hold ' + (sciT0[2] ? sciT0[2].works : 0) + ' works and 0 records in this harvest. The affiliation belongs to the author, not to the study.'
    ) : '';

    /* §12 · GIRE · confirmed Italian herbicide-resistance cases. Real before
       this pass and real after it; what changed is that it now reads
       AM.collections.resistance instead of window.ITALY_INGEST, and it no
       longer derives a mode of action.

       Why the MoA went: MECHANISM arrives { state: NOT_APPROVED_FOR_DISPLAY }
       on 34/34 records because the ingested field is the analyst's Portuguese
       working note with the fact inline. The previous code regex-matched HRAC
       groups out of that note — parsing a research note for a fact, which this
       block's own rule forbids. The species, family, crop, first-case year,
       regions and authority are published instead; the mechanism is declared
       unpublished rather than reconstructed. */
    const sciMechUnknown = sciL('MECCANISMO NON PUBBLICATO', 'MECHANISM NOT PUBLISHED');
    const sciHerb = (AM && AM.products ? AM.products : []).filter((p) => String(p.line || '').toUpperCase() === 'HERBICIDA');
    const sciHerbTotal = sciHerb.length;
    const gireAll = sciRes0.map((r) => {
      /* §7 · A taxonomic name is never truncated at "(" — the parenthetical is
         part of the identification in "Schoenoplectus (Scirpus) mucronatus" and
         "Oryza sativa (L.) var. sylvatica". Only the analyst's own additions go:
         everything after an em dash, and a parenthesis that opens a synonym
         note ("(sinonimi na ficha: ...)"), which is prose, not nomenclature. */
      const spFull = String(r.species || '').split('—')[0].replace(/\s*\((?:sinonimi|sin[oó]nimos)\b[^)]*\)\s*/gi, ' ').replace(/\s+/g, ' ').trim();
      const spItRaw = String(r.speciesIt || '').split('—')[0].split('(')[0].split(',')[0].trim();
      /* Rule 11 · the Latin binomial is never translated away. The Italian
         vernacular the source supplies is added beside the crop, not put in
         place of the name — three separate Lolium records would otherwise all
         read "Loietto" and stop being distinguishable. */
      const spIt = (sciIT && spItRaw && !sciNOTE.test(spItRaw)) ? spItRaw : '';
      const sp = spFull;
      const genus = spFull.replace(/^\W+/, '').split(' ')[0];
      /* Genus overlap with a herbicide label is a reason to review, never a
         finding about a product and never an area figure. */
      const hits = sciHerb.filter((p) => (p.targets || []).some((x) => String(x).indexOf(genus) === 0));
      const cropRaw = String(r.crop || '').split('—')[0].split('(')[0].trim();
      const regions = sciUniq(String((r.regions || []).join('|')).split('|')
        .map((x) => String(x).split('—')[0].split('(')[0].trim())
        .filter((x) => x && x.length < 26 && !sciNOTE.test(x)));
      const fam = String(r.family || '').trim();
      const cropClean = (!cropRaw || sciNOTE.test(cropRaw)) ? sciL('coltura non dichiarata', 'crop not declared') : cropRaw.toLowerCase();
      return {
        id: r.id, species: sp || '—', speciesFull: spFull, speciesIt: spIt, family: fam,
        /* §6 · A research note is never parsed for a fact. The year is
           published only when the field is exactly four digits after the
           analyst's note is removed; 5 of 34 are a sentence saying the record
           does not state one, and those show an em dash. */
        year: (() => { const raw = String(r.firstCaseYear || '').split('—')[0].trim(); return /^\d{4}$/.test(raw) ? raw : '—'; })(),
        crop: cropClean,
        cropL: [spIt, cropClean, fam].filter(Boolean).join(' · '),
        /* The gate, not a hard-coded blank: if upstream ever approves a
           localized mechanism text it renders; today it never does. */
        mech: sciNar(r.mechanism) || sciMechUnknown,
        mechColor: sciNar(r.mechanism) ? '#F89E18' : '#8F8886',
        regions: regions.slice(0, 4).join(' · ') || sciL('regioni non risolte', 'regions not resolved'),
        /* §8 · Never an absolute negative. The denominator is counted from the
           data and the absence rule travels with the negative. */
        adamaCount: hits.length,
        adamaLabel: hits.length
          ? hits.length + '/' + sciHerbTotal + ' ' + (T.gireFound || 'ADAMA herbicide labels name this genus')
          : (T.gireNotFound || 'Not found among the herbicide labels in this reading'),
        adamaNote: hits.length ? '' : (T.absenceRule || sciAbsence),
        adamaColor: hits.length ? '#00B152' : '#8F8886',
      };
    }).sort((a, b) => b.adamaCount - a.adamaCount || a.species.localeCompare(b.species));
    const gireShown = gireAll.slice(0, s.gireAll ? gireAll.length : 8);
    const gireMore = gireAll.length - gireShown.length;
    const gireStats = { total: gireAll.length, linked: gireAll.filter((g) => g.adamaCount > 0).length, herbicides: sciHerbTotal };

    /* §12 · RECENT RESEARCH. 88 rows, sorted by the real PUBLISHED_AT
       descending so the word "recent" is true — the corpus spans 2019-2026 and
       the fixture's 36 rows were ordered by nothing.
       Gone with the fixture: the generated "why" sentence (it asserted timing
       and pressure relevance for a crop), the invented study area (the only
       geography upstream is COUNTRY_OF_FACT = IT on 88/88, a country, not a
       study location) and the per-record opportunity link (assigned in the
       fixture by `caseObjs[i % length]`). */
    const records = sciR0.slice().sort((a, b) => String(b.publishedAt).localeCompare(String(a.publishedAt))).map((r) => ({
      id: r.id, title: r.title, descriptor: r.title,
      year: r.year || sciUNK, publishedAt: r.publishedAt,
      institution: r.institution, author: r.author, venue: r.venue, doi: r.doi, url: r.url,
      crop: r.crop, issue: r.issue, themeKey: r.themeKey, themeTitle: r.themeTitle,
      category: (() => { const c = sciCat(r.issue); return Object.assign({}, c, { icon: c.iconAsset || '' }); })(),
      materialTypeL: sciVocab(SCI_MTYPE, r.materialType), materialRoleL: sciVocab(SCI_MROLE, r.materialRole),
      study: sciVocab(SCI_MTYPE, r.materialType) + ' · ' + sciVocab(SCI_MROLE, r.materialRole),
      /* The two free slots on the row's sub-line now carry the author and the
         venue, both 88/88 real, instead of generated prose and a fake region. */
      why: r.author, locationShort: r.venue,
      location: sciL('Italia · area di studio non dichiarata', 'Italy · study area not stated'),
      /* No external source states a business relevance for a paper. */
      bizRel: '', bizColor: '#8F8886',
      openImpact: () => r.themeKey && this.setState({ sciImpactId: r.themeKey }),
      /* The opportunity link is deleted, not emptied into a look-alike. */
      related: { issueL: '', region: '', id: null }, openCase: () => {},
    }));

    /* §12 · INSTITUTIONS. Derived, and much smaller and less Italian than the
       fixture's 12 hardcoded names: MEASURED 6 — University of Verona 27,
       University of Turin 25, University of Milan 16, Institute of Sciences of
       Food Production 15, INRAE 3 (France), Instituto de Agricultura Sostenible
       2 (Spain). This is the FIRST AUTHOR's affiliation on the record, which is
       a different thing from the per-theme INSTITUTIONS_TOP work counts below,
       and the two are never summed. The invented "type" ("University" /
       "National research body") was decided in the fixture by name.startsWith,
       so it is replaced by what the row actually is. */
    const sciInstTally = {};
    sciR0.forEach((r) => { if (r.institution) { (sciInstTally[r.institution] = sciInstTally[r.institution] || []).push(r); } });
    /* AM.collections.scienceInstitutions landed while this block was written and
       is the same derivation; it is preferred, with the local tally kept as the
       fallback so the screen still stands if the projection moves again. */
    const sciInst0 = (APP0 && APP0.scienceInstitutions)
      ? APP0.scienceInstitutions.records
      : Object.keys(sciInstTally).sort((a, b) => sciInstTally[b].length - sciInstTally[a].length || a.localeCompare(b))
        .map((name) => ({ id: 'SCI-INST-' + name.toUpperCase().replace(/[^A-Z0-9]+/g, '-').slice(0, 40), name, recordCount: sciInstTally[name].length }));
    const institutions = sciInst0.map((i) => ({
      id: i.id, name: i.name, records: i.recordCount, recordCount: i.recordCount,
      /* Replaces the fixture's invented classification. It is also the caveat
         the panel needs: two of these six are not Italian. */
      type: sciL('affiliazione del primo autore', 'first-author affiliation'),
      themes: sciUniq((sciInstTally[i.name] || []).map((r) => r.themeTitle)),
      themeLabel: sciUniq((sciInstTally[i.name] || []).map((r) => r.themeTitle)).slice(0, 2).join(' · ') || sciL('nessun tema abbinato', 'no matched theme'),
    }));

    /* §12 · PEOPLE · one directory. AM.collections.people is the merge of the
       bibliometric RESEARCHERS index (60) with the evidence-bearing public
       PEOPLE list (15), keyed on the diacritic-folded name. MEASURED: 9 of the
       15 are the same human under a different accent, so the directory is 66
       records over 65 distinct names, not 75. That merge is the model's, not
       this view's — the local fold below is only the fallback.

       ROLE and FACT_REGION are the analyst's "NAO SEI" sentence on 60/60
       researchers and the model nulls them. It does NOT null the public-people
       side, where 4 of 5 stated roles ("coordenador do GIRE", "membro do GIRE",
       "responsavel do setor", "formacao declarada em ...") and one organization
       ("canal proprio de viticultura") are Portuguese working prose. They are
       dropped here, and the model owes a guard on that side. */
    const sciFold = (v) => String(v || '').normalize('NFD').split('').filter((c) => { const n = c.charCodeAt(0); return n < 768 || n > 879; }).join('').toLowerCase().trim();
    const sciInitials = (n) => String(n || '?').split(' ').filter(Boolean).map((x) => x[0]).join('').slice(0, 3).toUpperCase();
    const SCI_ROLECAT = { RESEARCHER: 'RESEARCHERS', INSTITUTIONAL_EXPERT: 'INSTITUTIONAL EXPERTS', CREATOR: 'INFLUENCERS / CREATORS', COMPANY_PERSON: 'COMPANY PEOPLE' };
    const sciOrg = (v) => { const x = String(v || '').trim(); return (x && !sciNOTE.test(x) && /[A-Z]/.test(x)) ? x : sciUNK; };
    const sciPeople0 = (APP0 && APP0.people) ? APP0.people.records : (() => {
      const rows = sciP0.slice();
      const byN = {};
      rows.forEach((p) => { (byN[sciFold(p.name)] = byN[sciFold(p.name)] || []).push(p); });
      sciPP0.forEach((p) => { if (!byN[sciFold(p.name)]) rows.push(p); });
      return rows;
    })();
    const people = sciPeople0.map((p) => ({
      id: p.id, name: p.name, label: p.name, initials: sciInitials(p.name),
      roleCat: p.roleCat || SCI_ROLECAT[String(p.category || '').toUpperCase()] || String(p.category || '').replace(/_/g, ' ').toUpperCase(),
      category: p.category,
      /* An organization that is working prose rather than a name is not
         published. An organization is a proper noun and every real one in this
         package carries a capital; MEASURED, exactly 1 of 15 does not
         ("canal proprio de viticultura", a description written in Portuguese),
         and that one resolves to the unknown label. */
      org: sciOrg(p.org), orgLabel: sciOrg(p.orgLabel || p.org),
      institutions: p.institutions || [],
      orcid: p.orcid || null, openalexId: p.openalexId || null,
      themeKey: p.themeKey || null, theme: null, themeLabel: p.themeLabel || null,
      worksInScope: (p.worksInScope === undefined ? null : p.worksInScope),
      lastActivity: p.lastActivity || null,
      /* ONE clock: daysFromRef was computed by AM.daysFrom against REF. */
      last: p.lastActivity || sciUNK, lastDays: (p.daysFromRef === undefined ? null : p.daysFromRef),
      identityState: p.identityStatus || null,
      identityStateL: (SCI_IDENT[String(p.identityStatus || '').toUpperCase()] || [])[sciIT ? 0 : 1] || '',
      identityLabel: sciL('identità dichiarata dalla fonte', 'identity as stated by the source'),
      /* Role, field region, crops and issues are not observable for these
         people from the sources this portal reads. Declared, never inferred
         from the theme query they happen to sit in. */
      role: null, region: sciL('affiliazione, non luogo dello studio', 'affiliation, not a study location'),
      crops: [], issues: [], cropLabel: '—', issueLabel: '—', regionShort: '—',
      messages: [], signals: [], related: [], relatedCount: 0, signalCount: 0, contentCount: 0, recentTopic: '',
      isResearcher: p.isResearcher !== false, alsoIds: p.alsoIds || [],
      real: true,
      go: () => this.openPerson(p.id),
    }));

    /* §12 · The RESEARCHERS panel. The fixture attached a business judgement to
       a named real person ("POTENTIAL EXPERT TO WATCH · relevant to X ·
       technical watch and possible expert engagement"). Nothing external
       supports that, so both lines are replaced by what the index really says:
       works inside the monitored query, the theme the query belongs to, and the
       source's own identity status — which is never upgraded to "confirmed".
       Sorted by LAST_ACTIVITY descending (60/60 real, 2019-01-02 to
       2026-07-30); that is an ordering, not a ranking. */
    const researchers = people.filter((p) => p.isResearcher)
      .slice().sort((a, b) => String(b.lastActivity).localeCompare(String(a.lastActivity)))
      .slice(0, 8)
      .map((p) => Object.assign({}, p, {
        org: (p.institutions && p.institutions.length) ? p.institutions.join(' · ') : sciUNK,
        bizWhy: (p.worksInScope === null || p.worksInScope === undefined ? sciUNK : p.worksInScope + ' ' + sciL('lavori nella query del tema', 'works in the theme query')) + (p.themeLabel ? ' · ' + p.themeLabel : ''),
        bizUse: p.identityStateL,
        bizNote: '',
      }));

    /* §12 · THEME DETAIL. No fallback to the first theme: an id that is not a
       theme id renders an empty topic, because showing another theme's facts
       under the requested id is worse than showing nothing. The screen check
       passes a scienceRecord id here, so this path is exercised. */
    const th0 = sciAll.find((x) => x.id === s.themeId) || null;
    const thCat = th0 ? th0.category : (AM ? Object.assign({}, AM.CATEGORY_UI.unknown, { icon: '' }) : { color: '#8F8886', dark: '#3A3533', soft: '#B1A9A7', icon: '' });
    const thRaw = th0 ? sciT0.find((x) => x.id === th0.id) : null;
    const th = th0 ? Object.assign({}, th0, {
      hasTheme: true,
      category: thCat,
      /* Two different institution lists sit 20 lines apart in this screen and
         mean different things. This one is INSTITUTIONS_TOP: OpenAlex work
         counts for the whole theme query (11-12 per theme, 37 distinct across
         the five) — NOT the 6 first-author affiliations on the home screen.
         The per-institution number is deliberately NOT printed: MEASURED, the
         top entry on theme 001 reads 177 while the theme's own WORKS is 135,
         so it is not a subset of the works count and the source never says
         what it counts. Publishing it beside "135 works" would invite exactly
         the wrong subtraction. */
      institutions: (thRaw ? thRaw.topInstitutions : []).map((i) => i.name),
      instCount: thRaw ? thRaw.topInstitutions.length : 0,
      people: people.filter((p) => p.themeKey && thRaw && p.themeKey === thRaw.theme).slice(0, 4),
      records: sciR0.filter((r) => r.themeKey === th0.id)
        .slice().sort((a, b) => String(b.publishedAt).localeCompare(String(a.publishedAt))).slice(0, 6)
        .map((r) => ({
          id: r.id, descriptor: r.title, year: r.year || sciUNK, institution: r.institution,
          /* SHOW_UNKNOWN, not a borrowed region: there is no study area upstream. */
          location: sciL('non dichiarata', 'not stated'),
          related: { issueL: '', region: '' }, openCase: () => {},
        })),
      /* No trend exists upstream and none is substituted; AUTHORS_ACTIVE_SINCE_2024
         is a headcount and would be read as growth. */
      trend: '—', trendColor: '#8F8886', trendUpper: '',
      caseCount: '—', caseObjs: [],
      /* MEASURED: 3 of the 5 themes have 0 records in this harvest while still
         showing a works count of 71, 27 and 17. That contrast is the truth and
         the empty list must stay empty. */
      recordsEmpty: sciR0.filter((r) => r.themeKey === th0.id).length === 0,
    }) : {
      hasTheme: false, id: null, title: sciL('Tema non trovato', 'Topic not found'),
      cropL: '', issueL: '', note: sciL('nessun tema bibliometrico corrisponde a questo identificativo', 'no bibliometric topic matches this identifier'),
      category: thCat, works: '—', worksLabel: '—',
      trend: '—', trendColor: '#8F8886', trendUpper: '', caseCount: '—', caseObjs: [],
      institutions: [], instCount: 0, people: [], records: [], recordsEmpty: true,
    };

    // ---- archive
