-- MEDICAO POS-MIGRATION — SINTONIA EAME
--
-- GERADO por scripts/supabase_post_migration.py. Nao editar a mao.
--
-- ALVO: xhqebdweltytnghiavew (eame-sintonia-dev)
--
-- REFS RECUSADOS, ambos medidos:
--   hvtycqsrdtmxxodwcwph — branch develop: 51 tabelas herdadas e public.schema_migracao
--   odhdwvugikjdvkapbowe — parent: 732 objetos em storage, 19 tabelas com dado
--
-- ORDEM: 0000 (inventario) -> 0001 (migration) -> 0002 (a lei pega?)
--        -> 0003 (este: o que existe la dentro, e igual ao prometido?)
--
-- Tudo dentro de UMA transacao que termina em ROLLBACK. O banco sai como
-- entrou: nenhuma linha da fixture sobrevive, nenhum GRANT sobrevive.
--
-- As contagens vem do CATALOGO do Postgres, nao do texto do .sql. Contar
-- a palavra CREATE num arquivo prova que alguem digitou; so pg_class prova
-- que a tabela existe.
--
-- O GRANT: a migration cria os papeis e as politicas e NAO da GRANT.
-- Politica e permissao de LINHA, GRANT e permissao de TABELA — sem o
-- segundo, portal_reader nao le nem o pais dele. Este arquivo mede isso
-- em GRANT_PRESENTE_NA_MIGRATION (esperado NO, e NO e o estado de hoje,
-- nao uma falha deste teste) e da o GRANT aqui dentro so para conseguir
-- provar que a POLICY isola. O ROLLBACK leva o GRANT junto.

BEGIN;
SET search_path TO sintonia, public;

-- ordem e IDENTITY, nao serial, de proposito: com serial o portal_reader
-- precisaria de USAGE na sequence para inserir a propria medicao, e o nome
-- do schema temporario muda a cada sessao. Coluna identity herda o
-- privilegio da tabela e nao pede GRANT nenhum.
CREATE TEMP TABLE _resultado (
  ordem bigint GENERATED BY DEFAULT AS IDENTITY, nome text, tipo text,
  esperado text, encontrado text, veredito text) ON COMMIT DROP;

-- ── FIXTURE ────────────────────────────────────────────────────────
DO $fx$ BEGIN

  insert into source (source_id, source_name, source_role, country, access_state)
       values ('SRC-P', 'boletim fitosanitario', 'registro oficial', 'ES', 'OPEN');

  insert into source_snapshot (snapshot_id, source_id, captured_at, content_hash,
                               artifact_ref, artifact_language)
       values ('SNAP-P', 'SRC-P', timestamptz '2026-08-30 10:00:00+00',
               'hash-do-artefato', 's3://snap/p.html', 'es');

  insert into geo_anchor (geo_id, country, region, geo_resolution)
       values ('GEO-P-ES', 'ES', 'Andalucia', 'NUTS2'),
              ('GEO-P-IT', 'IT', 'Veneto', 'NUTS2'),
              ('GEO-P-FR', 'FR', 'Occitanie', 'NUTS2');

  -- ORIGINAL_TEXT na lingua da fonte, sem edicao. Este texto e o que os testes
  -- de preservacao vao procurar byte a byte.
  insert into evidence (evidence_id, source_id, snapshot_id, source_location_country,
                        fact_location_geo_id, source_language, evidence_level,
                        original_text, source_published_at, captured_at)
       values ('EV-P', 'SRC-P', 'SNAP-P', 'ES', 'GEO-P-ES', 'es', 'MEASURED',
               'se ha detectado mildiu en vinedo en Andalucia',
               date '2026-08-29', timestamptz '2026-08-30 10:00:00+00');

  insert into source_provenance (evidence_id, source_id, snapshot_id, original_ref,
                                 as_of_date)
       values ('EV-P', 'SRC-P', 'SNAP-P', 'https://origem.example/boletim',
               date '2026-08-29');

  insert into publish_run (publish_run_id, pipeline_version, schema_version, status,
                           shadow_validation_passed)
       values ('RUN-P', 'pos-migration', '0.1.0-draft', 'PUBLISHED', true);

  insert into publish_run_freeze (publish_run_id, repository, path, commit_sha, hose_id)
       values ('RUN-P', 'lucianodalondon-sys/eame-sintonia',
               'data/samples/IT-T4-001/IT-T4-001-adama-expiries.json',
               'd7b289425c5e436f3ce68e367b8706e11910f43b', 'H2');

  -- um objeto por pais: e a unica forma de o isolamento significar alguma coisa
  insert into attention_object (attention_object_id, object_type, country,
                                attention_state, publish_run_id)
       values ('AO-P-ES', 'PHENOMENON_CASE', 'ES', 'ATTENTION_READY', 'RUN-P'),
              ('AO-P-IT', 'REGULATORY_DEADLINE', 'IT', 'FORMING', 'RUN-P'),
              ('AO-P-FR', 'PHENOMENON_CASE', 'FR', 'NEEDS_EVIDENCE', 'RUN-P');

  insert into attention_object_evidence (attention_object_id, evidence_id, role)
       values ('AO-P-ES', 'EV-P', 'PRIMARY');

  insert into storage_provenance (subject_kind, subject_id, source_backend, repository,
                                  path, commit_sha, publish_run_id, source_id,
                                  snapshot_id, as_of_date)
       values ('attention_object', 'AO-P-ES', 'GITHUB', 'lucianodalondon-sys/eame-sintonia',
               'data/samples/IT-T4-001/IT-T4-001-adama-expiries.json',
               'd7b289425c5e436f3ce68e367b8706e11910f43b', 'RUN-P', 'SRC-P', 'SNAP-P', date '2026-08-29');

  -- UM objeto, TRES representacoes. Nao tres objetos.
  insert into attention_object_representation (attention_object_id, language, title,
                                               summary, is_translation,
                                               translation_provenance,
                                               translation_quality)
       values ('AO-P-ES', 'es', 'Mildiu en vinedo', 'resumen en espanol',
               false, null, null),
              ('AO-P-ES', 'en', 'Downy mildew in vineyard', 'summary in english',
               true, 'traducao automatica revisada', 'MACHINE_REVIEWED'),
              ('AO-P-ES', 'pt', 'Mildio em vinha', 'resumo em portugues',
               true, 'traducao automatica', 'MACHINE_UNREVIEWED');

  -- texto canonico e traducao moram em tabelas diferentes, de proposito
  insert into content_entity (canonical_entity_id, entity_kind, source_language,
                              original_text, evidence_id)
       values ('CE-P', 'EVIDENCE_QUOTE', 'es',
               'se ha detectado mildiu en vinedo en Andalucia', 'EV-P');

  insert into content_translation (canonical_entity_id, translation_language,
                                   translated_text, translation_provenance,
                                   translation_quality, source_text_hash)
       values ('CE-P', 'pt', 'foi detectado mildio em vinha na Andaluzia',
               'traducao automatica', 'MACHINE_UNREVIEWED', 'hash-do-original');

END $fx$;

-- ── ESTRUTURA, MULTILINGUE, PROVENIENCIA ───────────────────────────
INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'TABLES_ACTUAL', 'ESTRUTURA', '57', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '57' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(*) from pg_class where relkind in ('r','p') and relnamespace = (select oid from pg_namespace where nspname = 'sintonia')) s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'VIEWS_ACTUAL', 'ESTRUTURA', '13', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '13' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(*) from pg_class where relkind = 'v' and relnamespace = (select oid from pg_namespace where nspname = 'sintonia')) s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'RPCS_ACTUAL', 'ESTRUTURA', '4', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '4' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(*) from pg_proc where pronamespace = (select oid from pg_namespace where nspname = 'sintonia') and proretset = true) s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'RLS_HELPER_FUNCTIONS', 'ESTRUTURA', '1', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '1' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(*) from pg_proc where pronamespace = (select oid from pg_namespace where nspname = 'sintonia') and proretset = false) s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'RLS_ENABLED_TABLES', 'ESTRUTURA', '57', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '57' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(*) from pg_class where relkind in ('r','p') and relnamespace = (select oid from pg_namespace where nspname = 'sintonia') and relrowsecurity = true) s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'TABLES_WITHOUT_RLS', 'ESTRUTURA', '0', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '0' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(*) from pg_class where relkind in ('r','p') and relnamespace = (select oid from pg_namespace where nspname = 'sintonia') and relrowsecurity = false) s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'RLS_POLICIES_ACTUAL', 'ESTRUTURA', '82', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '82' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(*) from pg_policies where schemaname = 'sintonia') s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'TABLES_WITHOUT_POLICY', 'ESTRUTURA', '0', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '0' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(*) from pg_class c where c.relkind in ('r','p') and c.relnamespace = (select oid from pg_namespace where nspname = 'sintonia') and not exists (select 1 from pg_policy p where p.polrelid = c.oid)) s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'GRANT_PRESENTE_NA_MIGRATION', 'ACHADO', 'NO', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = 'NO' THEN 'PASS' ELSE 'FAIL' END
  FROM (select case when has_table_privilege('portal_reader', 'sintonia.attention_object', 'SELECT') then 'YES' else 'NO' end) s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'MULTILINGUAL_ONE_OBJECT_MULTI_REPRESENTATION', 'MULTILINGUE', '1|3', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '1|3' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(distinct attention_object_id) || '|' || count(*) from attention_object_representation where attention_object_id = 'AO-P-ES') s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'ORIGINAL_TEXT_PRESERVED_EVIDENCE', 'MULTILINGUE', 'se ha detectado mildiu en vinedo en Andalucia', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = 'se ha detectado mildiu en vinedo en Andalucia' THEN 'PASS' ELSE 'FAIL' END
  FROM (select original_text from evidence where evidence_id = 'EV-P') s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'ORIGINAL_TEXT_KEEPS_SOURCE_LANGUAGE', 'MULTILINGUE', 'es', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = 'es' THEN 'PASS' ELSE 'FAIL' END
  FROM (select source_language::text from evidence where evidence_id = 'EV-P') s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'TRANSLATION_SEPARATE_TABLE', 'MULTILINGUE', 'se ha detectado mildiu en vinedo en Andalucia|foi detectado mildio em vinha na Andaluzia', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = 'se ha detectado mildiu en vinedo en Andalucia|foi detectado mildio em vinha na Andaluzia' THEN 'PASS' ELSE 'FAIL' END
  FROM (select ce.original_text || '|' || ct.translated_text from content_entity ce join content_translation ct on ct.canonical_entity_id = ce.canonical_entity_id where ce.canonical_entity_id = 'CE-P') s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'TRANSLATION_DECLARES_PROVENANCE', 'MULTILINGUE', '2', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '2' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(*) from attention_object_representation where attention_object_id = 'AO-P-ES' and is_translation = true and translation_provenance is not null) s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'RPC_FALLBACK_USA_A_LINGUA_PEDIDA', 'MULTILINGUE', 'es|NO', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = 'es|NO' THEN 'PASS' ELSE 'FAIL' END
  FROM (select r.language::text || '|' || r.fallback_used from resolve_representation('AO-P-ES', 'es') r) s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'RPC_FALLBACK_CAI_PARA_EN', 'MULTILINGUE', 'en|YES', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = 'en|YES' THEN 'PASS' ELSE 'FAIL' END
  FROM (select r.language::text || '|' || r.fallback_used from resolve_representation('AO-P-ES', 'fr') r) s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'RPC_NAO_INVENTA_TRADUCAO', 'MULTILINGUE', 'NO_REPRESENTATION_AVAILABLE', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = 'NO_REPRESENTATION_AVAILABLE' THEN 'PASS' ELSE 'FAIL' END
  FROM (select r.fallback_used from resolve_representation('AO-P-IT', 'it') r) s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'PROVENANCE_END_TO_END', 'PROVENIENCIA', 'AO-P-ES|EV-P|SRC-P|SNAP-P|RUN-P|d7b289425c5e436f3ce68e367b8706e11910f43b', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = 'AO-P-ES|EV-P|SRC-P|SNAP-P|RUN-P|d7b289425c5e436f3ce68e367b8706e11910f43b' THEN 'PASS' ELSE 'FAIL' END
  FROM (select o.attention_object_id || '|' || e.evidence_id || '|' || s.source_id || '|' || sn.snapshot_id || '|' || pr.publish_run_id || '|' || prf.commit_sha from attention_object o join attention_object_evidence aoe on aoe.attention_object_id = o.attention_object_id join evidence e on e.evidence_id = aoe.evidence_id join source s on s.source_id = e.source_id join source_snapshot sn on sn.snapshot_id = e.snapshot_id join publish_run pr on pr.publish_run_id = o.publish_run_id join publish_run_freeze prf on prf.publish_run_id = pr.publish_run_id where o.attention_object_id = 'AO-P-ES') s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'PROVENANCE_COMMIT_TEM_40_CARACTERES', 'PROVENIENCIA', '40', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '40' THEN 'PASS' ELSE 'FAIL' END
  FROM (select length(commit_sha)::text from publish_run_freeze where publish_run_id = 'RUN-P') s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'PROVENANCE_VIEW_CHEGA_NO_COMMIT', 'PROVENIENCIA', 'd7b289425c5e436f3ce68e367b8706e11910f43b', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = 'd7b289425c5e436f3ce68e367b8706e11910f43b' THEN 'PASS' ELSE 'FAIL' END
  FROM (select commit_sha from v_publish_provenance where attention_object_id = 'AO-P-ES' limit 1) s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'PROVENANCE_SOURCE_LOCATION_NAO_E_FACT_LOCATION', 'PROVENIENCIA', 'ES|GEO-P-ES', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = 'ES|GEO-P-ES' THEN 'PASS' ELSE 'FAIL' END
  FROM (select source_location_country || '|' || fact_location_geo_id from evidence where evidence_id = 'EV-P') s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'PROVENANCE_GITHUB_E_SUPABASE_SEPARADOS', 'PROVENIENCIA', 'GITHUB|0', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = 'GITHUB|0' THEN 'PASS' ELSE 'FAIL' END
  FROM (select source_backend::text || '|' || (case when table_or_view is null then 0 else 1 end)::text from storage_provenance where subject_id = 'AO-P-ES') s(v);

INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'PROVENANCE_OBJETO_SEM_EVIDENCIA_NAO_TEM_CADEIA', 'PROVENIENCIA', '0', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '0' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(*) from attention_object o join attention_object_evidence aoe on aoe.attention_object_id = o.attention_object_id where o.attention_object_id = 'AO-P-FR') s(v);

-- ── ISOLAMENTO POR PAIS ────────────────────────────────────────────
--
-- O GRANT abaixo NAO esta na migration. Ele existe so dentro desta
-- transacao, para que a policy tenha o que filtrar. Sem ele o resultado
-- de todo teste de isolamento seria zero — e zero por falta de GRANT nao
-- prova isolamento nenhum: prova que a porta esta trancada por fora.
GRANT USAGE ON SCHEMA sintonia TO portal_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA sintonia TO portal_reader;
GRANT ALL ON _resultado TO portal_reader;

SET LOCAL sintonia.countries = '';
SET LOCAL ROLE portal_reader;
INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'COUNTRY_ISOLATION_DENY_BY_DEFAULT', 'ISOLAMENTO', '0', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '0' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(*) from attention_object) s(v);
RESET ROLE;

SET LOCAL sintonia.countries = 'ES';
SET LOCAL ROLE portal_reader;
INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'COUNTRY_ISOLATION_ES', 'ISOLAMENTO', 'AO-P-ES', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = 'AO-P-ES' THEN 'PASS' ELSE 'FAIL' END
  FROM (select coalesce(string_agg(attention_object_id, ',' order by attention_object_id), '') from attention_object) s(v);
RESET ROLE;

SET LOCAL sintonia.countries = 'IT';
SET LOCAL ROLE portal_reader;
INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'COUNTRY_ISOLATION_IT', 'ISOLAMENTO', 'AO-P-IT', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = 'AO-P-IT' THEN 'PASS' ELSE 'FAIL' END
  FROM (select coalesce(string_agg(attention_object_id, ',' order by attention_object_id), '') from attention_object) s(v);
RESET ROLE;

SET LOCAL sintonia.countries = 'FR';
SET LOCAL ROLE portal_reader;
INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'COUNTRY_ISOLATION_FR', 'ISOLAMENTO', 'AO-P-FR', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = 'AO-P-FR' THEN 'PASS' ELSE 'FAIL' END
  FROM (select coalesce(string_agg(attention_object_id, ',' order by attention_object_id), '') from attention_object) s(v);
RESET ROLE;

SET LOCAL sintonia.countries = 'ES';
SET LOCAL ROLE portal_reader;
INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'COUNTRY_ISOLATION_ES_NAO_VE_IT_NEM_FR', 'ISOLAMENTO', '0', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '0' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(*) from attention_object where country in ('IT','FR')) s(v);
RESET ROLE;

SET LOCAL sintonia.countries = 'ES';
SET LOCAL ROLE portal_reader;
INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'COUNTRY_ISOLATION_GEO_ES', 'ISOLAMENTO', 'GEO-P-ES', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = 'GEO-P-ES' THEN 'PASS' ELSE 'FAIL' END
  FROM (select coalesce(string_agg(geo_id, ',' order by geo_id), '') from geo_anchor) s(v);
RESET ROLE;

SET LOCAL sintonia.countries = 'ES';
SET LOCAL ROLE portal_reader;
INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'COUNTRY_ISOLATION_FILHA_HERDA_O_PAIS', 'ISOLAMENTO', '3', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '3' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(*) from attention_object_representation) s(v);
RESET ROLE;

SET LOCAL sintonia.countries = 'IT';
SET LOCAL ROLE portal_reader;
INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'COUNTRY_ISOLATION_FILHA_NEGA_PAIS_ALHEIO', 'ISOLAMENTO', '0', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '0' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(*) from attention_object_representation) s(v);
RESET ROLE;

SET LOCAL sintonia.countries = 'ES,FR';
SET LOCAL ROLE portal_reader;
INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
SELECT 'COUNTRY_ISOLATION_MULTIPAIS', 'ISOLAMENTO', '2', coalesce(v::text, '<NULO>'),
       CASE WHEN coalesce(v::text, '<NULO>') = '2' THEN 'PASS' ELSE 'FAIL' END
  FROM (select count(*) from attention_object) s(v);
RESET ROLE;

RESET ROLE;
SET LOCAL sintonia.countries = '';

-- ── NEGATIVAS: so a recusa prova que a lei pega ────────────────────
--
-- Cada bloco tenta gravar uma linha proibida. PASS e quando o Postgres
-- levanta excecao. Se a insercao passar, o veredito e FAIL — e o
-- SAVEPOINT desfaz a linha para nao contaminar o que vem depois.

DO $neg$
DECLARE aceito boolean := false; estado text := '';
BEGIN
  BEGIN
    insert into publish_run (publish_run_id, pipeline_version, schema_version, status, shadow_validation_passed) values ('RUN-X', 'x', 'x', 'PUBLISHED', false);
    aceito := true;
    RAISE EXCEPTION 'DESFAZER_A_LINHA_QUE_NAO_DEVIA_TER_ENTRADO';
  EXCEPTION WHEN others THEN
    estado := SQLSTATE;
  END;
  INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
  VALUES ('NEG_PUBLICADO_SEM_SOMBRA_APROVADA', 'NEGATIVA', 'RECUSADO',
          CASE WHEN aceito THEN 'ACEITO' ELSE 'RECUSADO: ' || estado END,
          CASE WHEN aceito THEN 'FAIL' ELSE 'PASS' END);
END $neg$;  -- publicar sem a validacao sombra ter passado

DO $neg$
DECLARE aceito boolean := false; estado text := '';
BEGIN
  BEGIN
    insert into storage_provenance (subject_kind, subject_id, source_backend, repository, path) values ('attention_object', 'AO-P-ES', 'GITHUB', 'r', 'p');
    aceito := true;
    RAISE EXCEPTION 'DESFAZER_A_LINHA_QUE_NAO_DEVIA_TER_ENTRADO';
  EXCEPTION WHEN others THEN
    estado := SQLSTATE;
  END;
  INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
  VALUES ('NEG_GITHUB_SEM_COMMIT', 'NEGATIVA', 'RECUSADO',
          CASE WHEN aceito THEN 'ACEITO' ELSE 'RECUSADO: ' || estado END,
          CASE WHEN aceito THEN 'FAIL' ELSE 'PASS' END);
END $neg$;  -- proveniencia GitHub sem o commit que congela o arquivo

DO $neg$
DECLARE aceito boolean := false; estado text := '';
BEGIN
  BEGIN
    insert into storage_provenance (subject_kind, subject_id, source_backend, repository, path, commit_sha, table_or_view, db_schema, primary_key) values ('attention_object', 'AO-P-ES', 'GITHUB', 'r', 'p', 'd7b289425c5e436f3ce68e367b8706e11910f43b', 'attention_object', 'sintonia', 'AO-P-ES');
    aceito := true;
    RAISE EXCEPTION 'DESFAZER_A_LINHA_QUE_NAO_DEVIA_TER_ENTRADO';
  EXCEPTION WHEN others THEN
    estado := SQLSTATE;
  END;
  INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
  VALUES ('NEG_BACKENDS_MISTURADOS', 'NEGATIVA', 'RECUSADO',
          CASE WHEN aceito THEN 'ACEITO' ELSE 'RECUSADO: ' || estado END,
          CASE WHEN aceito THEN 'FAIL' ELSE 'PASS' END);
END $neg$;  -- a mesma linha dizendo que veio do GitHub e do Supabase

DO $neg$
DECLARE aceito boolean := false; estado text := '';
BEGIN
  BEGIN
    insert into attention_object_representation (attention_object_id, language, title, is_translation) values ('AO-P-IT', 'en', 'title', true);
    aceito := true;
    RAISE EXCEPTION 'DESFAZER_A_LINHA_QUE_NAO_DEVIA_TER_ENTRADO';
  EXCEPTION WHEN others THEN
    estado := SQLSTATE;
  END;
  INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
  VALUES ('NEG_TRADUCAO_SEM_PROVENIENCIA', 'NEGATIVA', 'RECUSADO',
          CASE WHEN aceito THEN 'ACEITO' ELSE 'RECUSADO: ' || estado END,
          CASE WHEN aceito THEN 'FAIL' ELSE 'PASS' END);
END $neg$;  -- representacao marcada como traducao sem dizer quem traduziu

DO $neg$
DECLARE aceito boolean := false; estado text := '';
BEGIN
  BEGIN
    insert into content_translation (canonical_entity_id, translation_language, translated_text, translation_provenance) values ('CE-P', 'UNKNOWN', 't', 'p');
    aceito := true;
    RAISE EXCEPTION 'DESFAZER_A_LINHA_QUE_NAO_DEVIA_TER_ENTRADO';
  EXCEPTION WHEN others THEN
    estado := SQLSTATE;
  END;
  INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
  VALUES ('NEG_TRADUCAO_PARA_LINGUA_QUE_NAO_E_LINGUA', 'NEGATIVA', 'RECUSADO',
          CASE WHEN aceito THEN 'ACEITO' ELSE 'RECUSADO: ' || estado END,
          CASE WHEN aceito THEN 'FAIL' ELSE 'PASS' END);
END $neg$;  -- UNKNOWN e MULTILINGUAL nao sao alvo de traducao

DO $neg$
DECLARE aceito boolean := false; estado text := '';
BEGIN
  BEGIN
    insert into attention_object_representation (attention_object_id, language, title) values ('AO-P-ES', 'es', 'outro titulo');
    aceito := true;
    RAISE EXCEPTION 'DESFAZER_A_LINHA_QUE_NAO_DEVIA_TER_ENTRADO';
  EXCEPTION WHEN others THEN
    estado := SQLSTATE;
  END;
  INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
  VALUES ('NEG_DUAS_REPRESENTACOES_NA_MESMA_LINGUA', 'NEGATIVA', 'RECUSADO',
          CASE WHEN aceito THEN 'ACEITO' ELSE 'RECUSADO: ' || estado END,
          CASE WHEN aceito THEN 'FAIL' ELSE 'PASS' END);
END $neg$;  -- um objeto tem UMA representacao por lingua, nao duas

DO $neg$
DECLARE aceito boolean := false; estado text := '';
BEGIN
  BEGIN
    insert into geo_anchor (geo_id, country, locality_text, geometry, geo_resolution, geometry_source_id) values ('GEO-X', 'ES', 'un pueblo', '{"type":"Point"}'::jsonb, 'LOCALITY_TEXT', 'SRC-P');
    aceito := true;
    RAISE EXCEPTION 'DESFAZER_A_LINHA_QUE_NAO_DEVIA_TER_ENTRADO';
  EXCEPTION WHEN others THEN
    estado := SQLSTATE;
  END;
  INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
  VALUES ('NEG_LOCALITY_TEXT_COM_PONTO', 'NEGATIVA', 'RECUSADO',
          CASE WHEN aceito THEN 'ACEITO' ELSE 'RECUSADO: ' || estado END,
          CASE WHEN aceito THEN 'FAIL' ELSE 'PASS' END);
END $neg$;  -- texto de localidade nao vira ponto no mapa

DO $neg$
DECLARE aceito boolean := false; estado text := '';
BEGIN
  BEGIN
    insert into geo_anchor (geo_id, country, geometry, geo_resolution) values ('GEO-Y', 'ES', '{"type":"Point"}'::jsonb, 'POINT');
    aceito := true;
    RAISE EXCEPTION 'DESFAZER_A_LINHA_QUE_NAO_DEVIA_TER_ENTRADO';
  EXCEPTION WHEN others THEN
    estado := SQLSTATE;
  END;
  INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
  VALUES ('NEG_GEOMETRIA_SEM_ORIGEM', 'NEGATIVA', 'RECUSADO',
          CASE WHEN aceito THEN 'ACEITO' ELSE 'RECUSADO: ' || estado END,
          CASE WHEN aceito THEN 'FAIL' ELSE 'PASS' END);
END $neg$;  -- geometria sem dizer de onde veio

DO $neg$
DECLARE aceito boolean := false; estado text := '';
BEGIN
  BEGIN
    insert into evidence (evidence_id, source_id, source_language, evidence_level, passage_start) values ('EV-X', 'SRC-P', 'es', 'PARTIAL', 10);
    aceito := true;
    RAISE EXCEPTION 'DESFAZER_A_LINHA_QUE_NAO_DEVIA_TER_ENTRADO';
  EXCEPTION WHEN others THEN
    estado := SQLSTATE;
  END;
  INSERT INTO _resultado (nome, tipo, esperado, encontrado, veredito)
  VALUES ('NEG_OFFSETS_SOZINHOS', 'NEGATIVA', 'RECUSADO',
          CASE WHEN aceito THEN 'ACEITO' ELSE 'RECUSADO: ' || estado END,
          CASE WHEN aceito THEN 'FAIL' ELSE 'PASS' END);
END $neg$;  -- inicio de trecho sem fim: meio recorte nao localiza nada

-- ── RESULTADO ──────────────────────────────────────────────────────
SELECT jsonb_pretty(jsonb_build_object(
  'DEV_PROJECT_REF_ESPERADO', 'xhqebdweltytnghiavew',
  'CONFERIR_O_REF', 'este SQL nao sabe onde esta rodando: quem cola confere',
  'TOTAL', (select count(*) from _resultado),
  'PASS', (select count(*) from _resultado where veredito = 'PASS'),
  'FAIL', (select count(*) from _resultado where veredito = 'FAIL'),
  'FALHAS', (select coalesce(jsonb_agg(to_jsonb(t)), '[]'::jsonb)
             from (select nome, tipo, esperado, encontrado from _resultado
                   where veredito = 'FAIL' order by ordem) t),
  'ACHADOS', (select coalesce(jsonb_agg(to_jsonb(t)), '[]'::jsonb)
              from (select nome, esperado, encontrado from _resultado
                    where tipo = 'ACHADO' order by ordem) t),
  'TUDO', (select jsonb_agg(to_jsonb(t) order by t.ordem)
           from (select * from _resultado) t)
)) AS medicao_pos_migration;

-- O banco sai como entrou.
ROLLBACK;
