// CONTRATOS DE FONTE — ITALIA V1
//
// Um contrato responde, de forma executavel:
//   quem e · onde esta · como encontro · o que espero receber · como sei que e o
//   documento certo · qual a identidade · qual a data · como sei que mudou ·
//   qual a frequencia · o que preservo · como falha · o que a falha significa.
//
// LEIS QUE ESTE ARQUIVO CARREGA (cada uma tem guarda em italy_contract_test.mjs):
//   HTTP_200                 != HEALTHY_SOURCE
//   EMPTY_LIST               != ZERO_DOCUMENTS      (lista vazia FALHA fechada)
//   SAME_URL                 != SAME_DOCUMENT       (hash novo = observacao nova)
//   DOCUMENT_ID              != BYTE_ID             (identidade semantica != SHA)
//   DECLARED_FREQUENCY       != OBSERVED_FREQUENCY
//   ACCESS_CLASSIFICATION    != ANALYTIC_VERDICT
//   SOURCE_VERDICT           != SOURCE_HEALTH
//   AGROCLIMATIC_SIGNAL      != PEST_OCCURRENCE
//   COMPANY_CLAIM            != REGULATORY_FACT
//   BROWSER_RENDERED_EXTRACT != RAW_PRESERVED
//   SAME_HASH                != DEGRADED            (corrigida em 2026-09-07, ver abaixo)
//   NO_CHANGE                != FAILURE
//   CAPTURE                  != DOCUMENT
//   NEW_HASH                 != NEW_SEMANTIC_FACT
//   MOVING_WINDOW            != NEW_DATASET_EVERY_DAY
//   FIRST_RUN                =  BASELINE
//
// CORRECAO DE LEI — 2026-09-07:
//   Eu havia escrito "hash repetido = DEGRADED / fonte parada". ERRADO e perigoso.
//   Uma fonte semanal consultada duas vezes no mesmo dia DEVE devolver o mesmo documento.
//   Atraso so existe com: EXPECTED_UPDATE + DEADLINE PROVADA + DEADLINE VENCIDA + SEM NOVA VERSAO.
//   Estados corretos: NO_CHANGE · EXPECTED_NO_CHANGE · UPDATE_DUE · OVERDUE_UPDATE · CADENCE_UNKNOWN

export const ROUTE_TYPES = ["STATIC_ROUTE", "PREDICTABLE_ROUTE", "DISCOVERED_ROUTE", "APPLICATION_ROUTE", "BROWSER_DISCOVERED_ROUTE"];
export const HEALTH_STATES = ["HEALTHY", "DEGRADED", "FAILED", "UNKNOWN"];

export const CONTRACTS = {

  "IT-T3-002": {
    OWNER_ID: "IT-OWN-007", OWNER: "Regione Campania — Servizio Fitosanitario Regionale",
    TERRITORY: "T3", VALUE: "P0",
    CANONICAL_ENTRY_URL: "https://agricoltura.regione.campania.it/difesa/bollettini/bollettini_<ANO>.html",
    DISCOVERY_METHOD: "abrir a pagina do ano; ela lista uma sub-pagina por provincia (AV, BN, CE, NA, SA); cada uma lista os PDFs",
    RETRIEVAL_METHOD: "GET direto no PDF",
    ROUTE_TYPE: "PREDICTABLE_ROUTE",
    ROUTE_TEMPLATE: "https://agricoltura.regione.campania.it/difesa/bollettini/bollettini_{ANO}/pdf/{PROV}-{DD}-{MM}.pdf",
    ROUTE_VARS: { ANO: "2026", PROV: ["AV", "BN", "CE", "NA", "SA"], DD: "dia com 2 digitos", MM: "mes com 2 digitos" },
    ACCESS_INSTRUMENT: "HTTP", AUTH_REQUIRED: false, BROWSER_REQUIRED: false, JS_REQUIRED: false,
    OUTPUT_TYPE: "PDF", EXPECTED_MIME: /^application\/pdf/, EXPECTED_SIGNATURE: "%PDF",
    MIN_BYTES: 100000,
    IDENTITY_KEYS: ["provincia", "data_do_boletim"],
    DOCUMENT_ID_RULE: "CAMPANIA:{PROV}:{DD-MM-ANO}",
    DOCUMENT_DATE_FIELD: "a data esta no NOME do arquivo (DD-MM); o ano vem do caminho",
    VERSION_FIELD: "nao ha versao explicita; uma data = uma edicao",
    EXPECTED_CONTENT_MARKERS: ["Monitoraggio", "Chimico", "Soglia"],
    EXPECTED_STRUCTURE: "blocos por avversita com Agronomico / Chimico / Soglia e substancia ativa nomeada",
    DECLARED_FREQUENCY: "o proprio site declara: semanal de 1 marco a 30 setembro (olivo ate fim de outubro), mensal fora disso",
    OBSERVED_FREQUENCY: "7D — provado por 14 edicoes de SA em 2026 espacadas exatamente 7 dias",
    UPDATE_BEHAVIOR: "ADITIVO — cada edicao ganha arquivo proprio, a anterior permanece",
    HISTORICAL_OR_FORWARD: "HISTORICAL", ARCHIVE_REQUIREMENT: "NORMAL",
    EXPECTED_FAILURES: ["404 numa data sem edicao (esperado, nao e falha da fonte)", "HTML no lugar de PDF = FAILED", "PDF abaixo de 100 KB = suspeito"],
    FAIL_CLOSED_RULE: "se o corpo nao comecar com %PDF, e FAILED — nunca registrar como boletim",
    FALLBACK: "voltar a pagina do ano e reler a lista da provincia",
    SOURCE_LOCATION_RULE: "Napoli (sede da Regiao) — fixo",
    FACT_LOCATION_RULE: "a PROVINCIA do proprio arquivo. NUNCA a sede.",
    EVIDENCE_CLASS: "TECHNICAL_GUIDELINE + OBSERVED_FIELD_SIGNAL pontual (rotulo Presente/Non Presente)",
    AUTOMATION_FEASIBILITY: "HIGH",
    NEGATIVE_CONTROL: { descricao: "pedir uma data que nao existe (SA-01-01.pdf)", esperado: "DOCUMENT_NOT_FOUND, nunca HTML tratado como boletim" }
  },

  "IT-T3-010": {
    OWNER_ID: "IT-OWN-012", OWNER: "A.P.OL. — Associazione tra Produttori Olivicoli, Lecce",
    TERRITORY: "T3", VALUE: "P0",
    CANONICAL_ENTRY_URL: "http://www.apol.it",
    aviso_de_esquema: "o site e HTTP, nao HTTPS. Tentar https:// nao resolve — foi o que escondeu esta fonte por uma rodada inteira.",
    DISCOVERY_METHOD: "a home lista os boletins com titulo, numero e periodo de validade",
    RETRIEVAL_METHOD: "GET direto no PDF",
    ROUTE_TYPE: "DISCOVERED_ROUTE",
    ROUTE_TEMPLATE: "http://www.apol.it/documenti/notizie/Bollettino_Mosca_dellOlivo_n_{N}_del_{DD}_{MM}_{AAAA}.pdf",
    aviso_de_rota: "o padrao de 2026 usa underscore (07_09_2026); o de 2025 usa hifen (20-10-2025). NAO adivinhar: descobrir no indice. Por isso ROUTE_TYPE = DISCOVERED, nao PREDICTABLE.",
    ACCESS_INSTRUMENT: "HTTP", AUTH_REQUIRED: false, BROWSER_REQUIRED: false, JS_REQUIRED: false,
    OUTPUT_TYPE: "PDF", EXPECTED_MIME: /^application\/pdf/, EXPECTED_SIGNATURE: "%PDF", MIN_BYTES: 300000,
    IDENTITY_KEYS: ["ano", "numero_da_edicao", "comprensorio"],
    DOCUMENT_ID_RULE: "APOL:{ANO}:N{NUMERO}:{COMPRENSORIO}",
    DOCUMENT_DATE_FIELD: "VALID_FROM e VALID_TO impressos no cabecalho: 'MOSCA DELLE OLIVE dd/mm/aaaa - dd/mm/aaaa'",
    VERSION_FIELD: "numero da edicao (n. 1..N por temporada)",
    EXPECTED_CONTENT_MARKERS: ["MOSCA DELLE OLIVE", "COMPRENSORIO"],
    EXPECTED_STRUCTURE: "cabecalho com periodo · comprensorio + lista de comuni · fase fenologica · capturas · % de infestacao · rotulo de tendencia · previsao diaria de 7 dias · texto tecnico com soglia",
    CAMPOS_A_EXTRAIR: ["ISSUE_NUMBER", "VALID_FROM", "VALID_TO", "COMPRENSORIO", "COMUNI", "PHENOLOGY", "TRAP_CAPTURES", "ACTIVE_INFESTATION_PERCENT", "TREND_LABEL", "TECHNICAL_RECOMMENDATION"],
    DECLARED_FREQUENCY: "o site nao declara cadencia em texto",
    OBSERVED_FREQUENCY: "7D — provado pelas DATAS dentro dos documentos preservados (VALID_FROM 31/08 e 07/09 = 7 dias exatos)",
    ressalva_da_cadencia: "so DOIS documentos foram preservados. A pagina lista 9 de 2026 e 14 de 2025, mas contar itens numa lista NAO e provar cadencia — a prova aqui vem do intervalo entre as datas impressas nos dois PDFs que temos.",
    UPDATE_BEHAVIOR: "ADITIVO", HISTORICAL_OR_FORWARD: "HISTORICAL", ARCHIVE_REQUIREMENT: "NORMAL",
    EXPECTED_FAILURES: ["indice vazio = FAILED (a home sempre lista boletins na temporada)", "HTTPS nao resolve — nao confundir com fonte fora do ar"],
    FAIL_CLOSED_RULE: "lista vazia no indice NAO e zero documentos: e FAILED",
    FALLBACK: "nenhum — fonte unica",
    SOURCE_LOCATION_RULE: "Lecce (sede) — fixo",
    FACT_LOCATION_RULE: "o COMPRENSORIO impresso no documento e os comuni listados. NUNCA a sede.",
    EVIDENCE_CLASS: "OBSERVED_FIELD_SIGNAL + COOPERATIVE_GUIDANCE",
    AUTOMATION_FEASIBILITY: "HIGH",
    NEGATIVE_CONTROL: { descricao: "indice sem nenhum link de boletim", esperado: "FAILED, nunca ZERO_DOCUMENTS" }
  },

  "IT-T3-008": {
    OWNER_ID: "IT-OWN-ARIF", OWNER: "ARIF Puglia — Agenzia regionale per le attivita irrigue e forestali",
    TERRITORY: "T3", VALUE: "P0",
    CANONICAL_ENTRY_URL: "https://www.agrometeopuglia.it/bollettini",
    OLD_ROUTE: "https://www.arifpuglia.it — DEAD (403 CloudFront, no curl E no navegador italiano)",
    CURRENT_ROUTE: "https://www.agrometeopuglia.it/bollettini — FOUND",
    DISCOVERY_METHOD: "a pagina lista o notiziario semanal corrente e o arquivo dos ultimos",
    RETRIEVAL_METHOD: "GET direto no PDF",
    ROUTE_TYPE: "PREDICTABLE_ROUTE",
    ROUTE_TEMPLATE: "https://www.agrometeopuglia.it/bollettino-elettronico/settimanale/{ANO}/Notiziario_Agrometeorologico_N{NN}_{DD-MM-AAAA}.pdf",
    ROTA_IRMA: "https://www.agrometeopuglia.it/bollettino-elettronico/quotidiano/{ANO}/Giornaliero_Meteorologico_N{NN}_{DD-MM-AAAA}.pdf — canal DIFERENTE (T2, so meteorologico). Nao misturar.",
    ACCESS_INSTRUMENT: "HTTP", AUTH_REQUIRED: false, BROWSER_REQUIRED: false, JS_REQUIRED: false,
    OUTPUT_TYPE: "PDF", EXPECTED_MIME: /^application\/pdf/, EXPECTED_SIGNATURE: "%PDF", MIN_BYTES: 1000000,
    IDENTITY_KEYS: ["ano", "numero_do_notiziario"],
    DOCUMENT_ID_RULE: "ARIF:SETTIMANALE:{ANO}:N{NUMERO}",
    DOCUMENT_DATE_FIELD: "no nome do arquivo E no cabecalho de cada pagina: 'n. 36 del 02 settembre 2026'",
    VERSION_FIELD: "numero sequencial + 'Anno XL' (ano da serie)",
    EXPECTED_CONTENT_MARKERS: ["Notiziario Agrometeorologico & Fitosanitario Regionale", "Situazione Fitosanitaria", "Programma di Difesa"],
    EXPECTED_STRUCTURE: "por cultura: Situazione Fenologica / Situazione Fitosanitaria / Programma di Difesa. 32 blocos de Situazione Fitosanitaria na edicao n.36.",
    LEITURA_RESOLVIDA_2026_09_07: "com pdftotext -layout a secao fitossanitaria le inteira: 32 blocos, 13 pragas com nome cientifico, soglie de 4-5%/5%/10%/20% e sostanze attive nomeadas (acetamiprid, flupyradifurone, deltametrina, spinosad, cyantraniliprole, pyriproxyfen, Bacillus thuringiensis).",
    LIMITE_CONHECIDO: "O NOME DA CULTURA E IMAGEM, nao texto. pdftotext le tudo menos o titulo da cultura. A cultura pode ser DERIVADA do nome cientifico da praga (mosca dell'olivo -> olivo; Plasmopara viticola -> vite), mas isso e DERIVACAO, nunca extracao. Marcar o campo como CROP_DERIVED, jamais como CROP_EXTRACTED.",
    DECLARED_FREQUENCY: "o site declara: semanal, com saida as quartas",
    OBSERVED_FREQUENCY: "7D — provado por 11 edicoes listadas (N26 24/06 ate N36 02/09) com espacamento exato de 7 dias",
    UPDATE_BEHAVIOR: "ADITIVO", HISTORICAL_OR_FORWARD: "HISTORICAL", ARCHIVE_REQUIREMENT: "NORMAL",
    EXPECTED_FAILURES: ["403 se alguem usar o dominio velho arifpuglia.it", "PDF abaixo de 1 MB e suspeito (as edicoes tem 2,7 MB)"],
    FAIL_CLOSED_RULE: "sem os tres marcadores de conteudo, e FAILED",
    FALLBACK: "reler a pagina /bollettini",
    SOURCE_LOCATION_RULE: "Bari (ARIF) — fixo",
    FACT_LOCATION_RULE: "Puglia regional; ha pontos de observacao citados no texto, ainda nao estruturados",
    EVIDENCE_CLASS: "OBSERVED_FIELD_SIGNAL + TECHNICAL_GUIDELINE (separar por bloco: 'Situazione Fitosanitaria' e OBSERVED, 'Programma di Difesa' e RECOMMENDED)",
    AUTOMATION_FEASIBILITY: "MEDIUM — rota e leitura sao faceis; o nome da cultura exige derivacao",
    NEGATIVE_CONTROL: { descricao: "PDF que nao contenha 'Situazione Fitosanitaria'", esperado: "FAILED" }
  },

  "IT-T3-005": {
    OWNER_ID: "IT-OWN-008", OWNER: "Terre dell'Etruria — Societa Cooperativa Agricola",
    TERRITORY: "T3", VALUE: "P0",
    CANONICAL_ENTRY_URL: "https://www.terretruria.it/monitoraggio",
    DISCOVERY_METHOD: "rota unica e fixa", RETRIEVAL_METHOD: "GET",
    ROUTE_TYPE: "STATIC_ROUTE",
    ACCESS_INSTRUMENT: "HTTP", AUTH_REQUIRED: false, BROWSER_REQUIRED: false, JS_REQUIRED: false,
    OUTPUT_TYPE: "HTML", EXPECTED_MIME: /^text\/html/, EXPECTED_SIGNATURE: "<", MIN_BYTES: 200000,
    IDENTITY_KEYS: ["periodo_do_bollettino"],
    DOCUMENT_ID_RULE: "TERRETRURIA:{PERIODO_INICIO}:{PERIODO_FIM}",
    IDENTITY_KEYS_DO_PONTO: ["point_id", "lat", "lon", "sampling_date"],
    DOCUMENT_DATE_FIELD: "'Bollettino del periodo dal DD-MM-AAAA al DD-MM-AAAA' no corpo",
    VERSION_FIELD: "nao ha numero de edicao — so o periodo",
    EXPECTED_CONTENT_MARKERS: ["Bollettino del periodo", "Legenda infestazione", "reports_points"],
    EXPECTED_STRUCTURE: "139 blocos <div class=reports_points> com nome, lat, lon, data de campionamento, infestacao e rotulo",
    CAMPOS_POR_PONTO: ["MONITORING_POINT_ID", "LAT", "LON", "DATE", "CROP", "PHENOLOGY", "INFESTATION_PERCENT", "ALERT", "TRAP (fechado por login)"],
    MIN_PONTOS: 100,
    FAIL_CLOSED_RULE: "menos de 100 pontos = FAILED. Zero pontos NUNCA e 'sem infestacao': e falha.",
    DECLARED_FREQUENCY: "o documento declara periodo fechado de 7 dias",
    OBSERVED_FREQUENCY: "NÃO SEI — uma unica edicao capturada. O site NAO guarda arquivo (/bollettini da 404).",
    UPDATE_BEHAVIOR: "SOBRESCRITA — uma edicao por vez, a anterior desaparece",
    HISTORICAL_OR_FORWARD: "FORWARD_ONLY", ARCHIVE_REQUIREMENT: "CRITICAL",
    EXPECTED_FAILURES: ["fora de temporada a pagina pode anunciar pausa (ha vestigio de 'riprendera a Giugno')", "camada de catture continua LOGIN_REQUIRED"],
    FALLBACK: "nenhum — nao ha arquivo publico",
    SOURCE_LOCATION_RULE: "Livorno (sede) — fixo",
    FACT_LOCATION_RULE: "COORDENADA do ponto (lat/lon com 4 casas). PREFERIR a coordenada ao municipio inferido, e NUNCA usar a sede.",
    EVIDENCE_CLASS: "OBSERVED_FIELD_SIGNAL + COOPERATIVE_GUIDANCE",
    AUTOMATION_FEASIBILITY: "HIGH",
    NEGATIVE_CONTROL: { descricao: "HTML sem nenhum bloco reports_points", esperado: "FAILED, nunca 'zero pontos monitorados'" }
  },

  "IT-T4-001": {
    OWNER_ID: "IT-OWN-MINSALUTE", OWNER: "Ministero della Salute — Open Data",
    TERRITORY: "T4", VALUE: "P0",
    CANONICAL_ENTRY_URL: "https://www.dati.salute.gov.it/it/dataset/fitosanitari/",
    DISCOVERY_METHOD: "a pagina lista CSV, XML, JSON e o dicionario; o nome do arquivo carrega a data",
    RETRIEVAL_METHOD: "GET no CSV",
    ROUTE_TYPE: "PREDICTABLE_ROUTE",
    ROUTE_TEMPLATE: "https://www.dati.salute.gov.it/sites/default/files/opendata/PROD_FTS_6_{AAAAMMDD}.csv",
    ACCESS_INSTRUMENT: "HTTP", AUTH_REQUIRED: false, BROWSER_REQUIRED: false, JS_REQUIRED: false,
    OUTPUT_TYPE: "CSV", EXPECTED_MIME: /csv|text|octet/, EXPECTED_SIGNATURE: "num_registrazione;",
    MIN_BYTES: 3000000, MIN_ROWS: 15000,
    IDENTITY_KEYS: ["data_do_dataset", "num_registrazione"],
    DOCUMENT_ID_RULE: "MINSALUTE:FTS6:{AAAAMMDD}  ·  por linha: {num_registrazione}",
    DOCUMENT_DATE_FIELD: "data no nome do arquivo",
    VERSION_FIELD: "a propria data do arquivo",
    EXPECTED_COLUMNS: ["num_registrazione", "denominazione_prodotto", "ragione_sociale", "data_registrazione", "data_scadenza_autorizzazione", "sostanze_attive"],
    DECLARED_FREQUENCY: "nao declarada em texto; ha RSS de aviso de atualizacao",
    OBSERVED_FREQUENCY: "NÃO SEI — uma unica data observada",
    UPDATE_BEHAVIOR: "ADITIVO por data de arquivo", HISTORICAL_OR_FORWARD: "NÃO SEI — nao se testou se arquivos antigos permanecem",
    ARCHIVE_REQUIREMENT: "ALTO ate provar que os antigos ficam",
    EXPECTED_FAILURES: ["CSV com menos de 15.000 linhas = DEGRADED", "coluna sostanze_attive ausente = FAILED"],
    FAIL_CLOSED_RULE: "faltando qualquer coluna obrigatoria, e FAILED",
    FALLBACK: "XML ou JSON da mesma pagina",
    SOURCE_LOCATION_RULE: "Roma", FACT_LOCATION_RULE: "ITALIA — nacional",
    EVIDENCE_CLASS: "REGULATORY_AUTHORIZATION",
    AUTOMATION_FEASIBILITY: "HIGH",
    NEGATIVE_CONTROL: { descricao: "CSV sem a coluna sostanze_attive", esperado: "FAILED" }
  },

  "IT-T1-001": {
    OWNER_ID: "IT-OWN-ISTAT", OWNER: "ISTAT", TERRITORY: "T1", VALUE: "P0",
    CANONICAL_ENTRY_URL: "https://esploradati.istat.it/SDMXWS/rest/data/IT1,101_1015_DF_DCSP_COLTIVAZIONI_2,1.0/",
    DISCOVERY_METHOD: "catalogo SDMX de dataflows (4.897 dataflows) — o de interesse e 101_1015_DF_DCSP_COLTIVAZIONI_2",
    RETRIEVAL_METHOD: "GET com Accept: application/vnd.sdmx.data+csv",
    ROUTE_TYPE: "APPLICATION_ROUTE",
    classificacao_honesta: "e API SDMX 2.1 documentada e sem chave — pode ser chamada de OFFICIAL_API. O PORTAL visual do mesmo dominio exige JavaScript e chegou a devolver erro; sao coisas diferentes.",
    ACCESS_INSTRUMENT: "HTTP", AUTH_REQUIRED: false, BROWSER_REQUIRED: false, JS_REQUIRED: false,
    OUTPUT_TYPE: "CSV", EXPECTED_MIME: /sdmx.*csv/, EXPECTED_SIGNATURE: "DATAFLOW,FREQ,REF_AREA",
    MIN_ROWS: 10000,
    IDENTITY_KEYS: ["DATAFLOW", "REF_AREA", "TYPE_OF_CROP", "TIME_PERIOD"],
    DOCUMENT_ID_RULE: "ISTAT:{DATAFLOW}:{REF_AREA}:{TYPE_OF_CROP}:{TIME_PERIOD}",
    DOCUMENT_DATE_FIELD: "TIME_PERIOD", VERSION_FIELD: "versao do dataflow (1.0)",
    EXPECTED_COLUMNS: ["DATAFLOW", "FREQ", "REF_AREA", "TYPE_OF_CROP", "TIME_PERIOD", "OBS_VALUE"],
    DECLARED_FREQUENCY: "serie anual", OBSERVED_FREQUENCY: "NÃO SEI — nao medido por captura repetida",
    UPDATE_BEHAVIOR: "REVISAO — series estatisticas sao revisadas; a mesma chave pode mudar de valor",
    HISTORICAL_OR_FORWARD: "HISTORICAL", ARCHIVE_REQUIREMENT: "NORMAL",
    EXPECTED_FAILURES: ["resposta lenta (13 s para 13,6 MB no catalogo)", "timeout curto devolve resposta parcial — NUNCA aceitar corpo truncado"],
    FAIL_CLOSED_RULE: "corpo sem o cabecalho DATAFLOW,FREQ,REF_AREA = FAILED",
    FALLBACK: "nenhum",
    SOURCE_LOCATION_RULE: "Roma", FACT_LOCATION_RULE: "REF_AREA da propria linha (provincia)",
    EVIDENCE_CLASS: "SERIE_OFICIAL_DE_PRODUCAO", AUTOMATION_FEASIBILITY: "HIGH",
    NEGATIVE_CONTROL: { descricao: "corpo truncado no meio", esperado: "FAILED, nunca contagem parcial tratada como total" }
  },

  "IT-T2-004": {
    OWNER_ID: "IT-OWN-SIAS", OWNER: "SIAS — Servizio Informativo Agrometeorologico Siciliano",
    TERRITORY: "T2", VALUE: "P1",
    CANONICAL_ENTRY_URL: "http://www.sias.regione.sicilia.it/NHEOWL0530_00.html",
    DISCOVERY_METHOD: "site em FRAMESET: home.htm > frameset_dati.htm > corpo_dati.htm > tabela por grandeza. A home direta devolve casca vazia.",
    RETRIEVAL_METHOD: "GET na pagina da grandeza",
    ROUTE_TYPE: "STATIC_ROUTE",
    ACCESS_INSTRUMENT: "HTTP", AUTH_REQUIRED: false, BROWSER_REQUIRED: false, JS_REQUIRED: false,
    OUTPUT_TYPE: "HTML", EXPECTED_MIME: /^text\/html/, EXPECTED_SIGNATURE: "<", MIN_BYTES: 30000,
    ENCODING: "iso-8859-1 — charset antigo; decodificar antes de comparar texto",
    IDENTITY_KEYS: ["table_type", "station", "window_end"],
    DOCUMENT_ID_RULE: "SIAS:{TABLE_TYPE}:{STATION}:{WINDOW_END}",
    LEI_CRITICA: "SAME_URL != SAME_DOCUMENT — a URL e fixa e a janela de dados anda todo dia. Deduplicar por URL PERDE dado. Deduplicar por (table_type, station, window_end) + SHA256.",
    DOCUMENT_DATE_FIELD: "'dal DD/MM/AAAA al DD/MM/AAAA' no cabecalho da tabela",
    VERSION_FIELD: "window_end",
    EXPECTED_CONTENT_MARKERS: ["Precipitazioni giornaliere", "Ultimo", "cumulate"],
    MIN_STATIONS: 20,
    DECLARED_FREQUENCY: "a rede declara 88 estacoes e dados diarios",
    OBSERVED_FREQUENCY: "NÃO SEI — uma captura so",
    UPDATE_BEHAVIOR: "SOBRESCRITA — janela movel de 11 dias na mesma URL",
    HISTORICAL_OR_FORWARD: "FORWARD_ONLY", ARCHIVE_REQUIREMENT: "CRITICAL",
    nota_de_arquivo: "existe 'SEZIONE RICHIESTA DATI' para serie historica, NAO testada. Ate testar, tratar como FORWARD_ONLY.",
    EXPECTED_FAILURES: ["tabela sem linhas de estacao = FAILED", "janela igual a da captura anterior = NO_CHANGE, NAO DEGRADED. So vira OVERDUE_UPDATE se houver cadencia PROVADA e o prazo tiver vencido — e a cadencia do SIAS ainda e NÃO SEI."],
    FAIL_CLOSED_RULE: "tabela vazia NAO e 'nao choveu': e FAILED",
    FALLBACK: "outra grandeza (temperatura) para confirmar se o servidor esta vivo",
    SOURCE_LOCATION_RULE: "Palermo", FACT_LOCATION_RULE: "a ESTACAO da linha",
    EVIDENCE_CLASS: "AGROCLIMATIC_SIGNAL",
    LEI: "AGROCLIMATIC_SIGNAL != PEST_OCCURRENCE",
    AUTOMATION_FEASIBILITY: "HIGH",
    NEGATIVE_CONTROL: { descricao: "tabela sem nenhuma linha de estacao", esperado: "FAILED, nunca zero chuva" }
  },

  "IT-T2-001": {
    OWNER_ID: "IT-OWN-ARPAE", OWNER: "ARPAE Emilia-Romagna", TERRITORY: "T2", VALUE: "P1",
    CANONICAL_ENTRY_URL: "https://www.arpae.it/it/temi-ambientali/meteo/report-meteo/bollettini-e-rapporti-agrometeo/bollettini-agrometeo/bollettini-{ANO}",
    OLD_ROUTE: "https://www.arpae.it/it/temi-ambientali/meteo/agrometeo — 404",
    CURRENT_ROUTE: "a rota acima",
    DISCOVERY_METHOD: "pagina do ano lista os PDFs numerados",
    RETRIEVAL_METHOD: "GET no PDF, SEM o sufixo /view",
    ARMADILHA: "o site e Plone. O link exibido termina em /view, que devolve a CASCA HTML da pagina, nao o PDF. SEMPRE remover /view e SEMPRE conferir a assinatura %PDF.",
    ROUTE_TYPE: "PREDICTABLE_ROUTE",
    ROUTE_TEMPLATE: ".../bollettini-{ANO}/{NN}_boll_agro_{AAAAMMDD}.pdf",
    ACCESS_INSTRUMENT: "HTTP", AUTH_REQUIRED: false, BROWSER_REQUIRED: false, JS_REQUIRED: false,
    OUTPUT_TYPE: "PDF", EXPECTED_MIME: /^application\/pdf/, EXPECTED_SIGNATURE: "%PDF", MIN_BYTES: 500000,
    IDENTITY_KEYS: ["ano", "numero_do_boletim"],
    DOCUMENT_ID_RULE: "ARPAE:{ANO}:N{NUMERO}",
    DOCUMENT_DATE_FIELD: "AAAAMMDD no nome do arquivo", VERSION_FIELD: "numero sequencial",
    DECLARED_FREQUENCY: "semanal", OBSERVED_FREQUENCY: "7D — provado por 7 edicoes seguidas na listagem",
    UPDATE_BEHAVIOR: "ADITIVO", HISTORICAL_OR_FORWARD: "HISTORICAL",
    ARCHIVE_REQUIREMENT: "BAIXO — ha arquivo por ano de 2021 a 2026",
    EXPECTED_FAILURES: ["usar /view devolve HTML com HTTP 200 — e FAILED"],
    FAIL_CLOSED_RULE: "corpo sem %PDF = FAILED",
    FALLBACK: "reler a pagina do ano",
    SOURCE_LOCATION_RULE: "Bologna", FACT_LOCATION_RULE: "Emilia-Romagna regional",
    EVIDENCE_CLASS: "AGROCLIMATIC_SIGNAL", LEI: "AGROCLIMATIC_SIGNAL != PEST_OCCURRENCE",
    AUTOMATION_FEASIBILITY: "HIGH",
    NEGATIVE_CONTROL: { descricao: "baixar a URL COM /view", esperado: "FAILED — HTML detectado, apesar do HTTP 200" }
  },

  "IT-T2-002": {
    OWNER_ID: "IT-OWN-ARPAV", OWNER: "ARPAV Veneto", TERRITORY: "T2", VALUE: "P1",
    CANONICAL_ENTRY_URL: "https://www.arpa.veneto.it/dati-ambientali/bollettini/agrometeo/agrometeoinforma",
    DISCOVERY_METHOD: "a pagina lista 32 links de zona; a leitura simples do HTML nao os mostrou — foram revelados pelo navegador",
    RETRIEVAL_METHOD: "GET direto no PDF da zona",
    ROUTE_TYPE: "BROWSER_DISCOVERED_ROUTE",
    ROUTE_TEMPLATE: "https://www.arpa.veneto.it/risorse/data-agrometeo/agrometeo/32zone/agro_{NN}.pdf  (NN = 01..32)",
    ACCESS_INSTRUMENT: "HTTP para baixar; BROWSER foi necessario para descobrir",
    AUTH_REQUIRED: false, BROWSER_REQUIRED: false, JS_REQUIRED: false,
    OUTPUT_TYPE: "PDF", EXPECTED_MIME: /^application\/pdf/, EXPECTED_SIGNATURE: "%PDF", MIN_BYTES: 200000,
    IDENTITY_KEYS: ["zone_id", "generated_at"],
    DOCUMENT_ID_RULE: "ARPAV:Z{ZONE_ID}:{GENERATED_AT}",
    DOCUMENT_DATE_FIELD: "NAO esta no nome do arquivo. Esta no metadado /CreationDate do proprio PDF (ex.: D:20260903160930+0200).",
    VERSION_FIELD: "CreationDate + SHA256",
    LEI_CRITICA: "SAME_URL != SAME_DOCUMENT — o nome do arquivo e FIXO e o conteudo e sobrescrito. Nunca deduplicar por URL. Cada SHA256 novo e uma observacao nova.",
    prova_medida: "agro_01 e agro_09 tem hashes diferentes E CreationDate diferentes (03/09 e 02/09) — as zonas publicam de forma independente",
    DECLARED_FREQUENCY: "o site declara: zonas 2-15/23/24 as segundas e quintas na primavera-verao, quartas no outono-inverno; as demais em outro calendario",
    OBSERVED_FREQUENCY: "NÃO SEI — uma captura so",
    UPDATE_BEHAVIOR: "SOBRESCRITA", HISTORICAL_OR_FORWARD: "FORWARD_ONLY", ARCHIVE_REQUIREMENT: "CRITICAL",
    EXPECTED_FAILURES: ["mesmo SHA numa nova captura = NO_CHANGE, NAO DEGRADED. Consultar duas vezes no mesmo dia uma fonte que publica 2x por semana DEVE devolver o mesmo documento — isso e o comportamento esperado.", "sem CreationDate = DEGRADED, porque ai falta identidade temporal"],
    FAIL_CLOSED_RULE: "corpo sem %PDF = FAILED",
    FALLBACK: "nenhum — o arquivo anterior ja foi perdido",
    SOURCE_LOCATION_RULE: "Teolo/Padova", FACT_LOCATION_RULE: "a ZONA do numero do arquivo",
    EVIDENCE_CLASS: "AGROCLIMATIC_SIGNAL", LEI: "AGROCLIMATIC_SIGNAL != PEST_OCCURRENCE",
    AUTOMATION_FEASIBILITY: "HIGH",
    NEGATIVE_CONTROL: { descricao: "capturar duas vezes seguidas sem mudanca", esperado: "SEEN_AGAIN + NO_CHANGE, com 0 objetos RAW novos. NUNCA DEGRADED, e NUNCA duas versoes." }
  },

  "IT-T7-002": {
    OWNER_ID: "IT-OWN-MASAF", OWNER: "MASAF", TERRITORY: "T7", VALUE: "P0",
    CANONICAL_ENTRY_URL: "https://www.masaf.gov.it/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/6063",
    DISCOVERY_METHOD: "navegar Politiche nazionali > Filiere > Organizzazioni di Produttori > Elenco nazionale; o anexo tem hash opaco na URL e MUDA a cada edicao",
    RETRIEVAL_METHOD: "descobrir o link do anexo na pagina e baixar",
    ROUTE_TYPE: "DISCOVERED_ROUTE",
    aviso_de_rota: "NAO fixar a URL do anexo. Ela contem um hash de conteudo que muda a cada nova edicao. Fixar quebraria silenciosamente na proxima publicacao.",
    ACCESS_INSTRUMENT: "HTTP", AUTH_REQUIRED: false, BROWSER_REQUIRED: false, JS_REQUIRED: false,
    OUTPUT_TYPE: "ODS", EXPECTED_MIME: /opendocument|octet|zip/, EXPECTED_SIGNATURE: "PK", MIN_BYTES: 30000,
    IDENTITY_KEYS: ["versao_da_publicacao", "codice_organizzazione"],
    DOCUMENT_ID_RULE: "MASAF:OP:{DATA_DA_EDICAO}  ·  por linha: {CODICE_IT}",
    DOCUMENT_DATE_FIELD: "no titulo do link: 'al 31 dicembre 2025 - aggiornato al 08.04.2026'",
    VERSION_FIELD: "a data de referencia + o 'REV.' quando existir",
    EXPECTED_COLUMNS: ["CODICE IT", "OP AOP", "SETTORE", "DENOMINAZIONE", "FORMA SOCIETARIA", "SEDE", "DATA DI RICONOSCIMENTO", "REGIONE"],
    CONTAGEM: {
      RAW_ROWS: 324, UNIQUE_ORGANIZATIONS: 272, OP: 264, AOP: 8, DUPLICADOS: 0,
      DUPLICATE_KEY_RULE: "chave = CODICE IT, casando /^IT\\//. Linha sem CODICE IT nao e organizacao.",
      WHY_DIFFERENT: "as 52 linhas a mais sao cabecalho, titulo do regulamento, linhas de secao por setor e linhas em branco do layout. ROWS != UNIQUE_ORGANIZATIONS.",
      CORRECAO: "publiquei 269 e depois 264. AMBOS ERRADOS. O 269 vinha de um parse por linha que perdia codigos; o 264 de um regex /^IT\\/[A-Z]+\\/\\d+/ que nao casa AOP, cujo codigo tem QUATRO segmentos (IT/OLI/AOP/001). Certo: 272."
    },
    DECLARED_FREQUENCY: "nao declarada em texto", OBSERVED_FREQUENCY: "1Y — tres edicoes anuais na mesma pagina (31/12/2023, 31/12/2024 REV.3, 31/12/2025)",
    UPDATE_BEHAVIOR: "ADITIVO", HISTORICAL_OR_FORWARD: "HISTORICAL", ARCHIVE_REQUIREMENT: "NORMAL",
    EXPECTED_FAILURES: ["planilha com menos de 200 organizacoes = DEGRADED", "coluna CODICE IT ausente = FAILED"],
    FAIL_CLOSED_RULE: "sem a coluna CODICE IT nao ha identidade — FAILED",
    FALLBACK: "as edicoes anteriores continuam na mesma pagina",
    SOURCE_LOCATION_RULE: "Roma", FACT_LOCATION_RULE: "a REGIONE e a SEDE declaradas em CADA LINHA da planilha.",
    POR_QUE_A_SEDE_VALE_AQUI: "excecao explicita, e a unica. Nas outras fontes a sede e a de QUEM PUBLICA, e usa-la seria localizar mal um fato de campo. Aqui o proprio fato registrado E o endereco: a linha diz onde aquela organizacao esta sediada. Nao ha fato de campo nenhum nesta fonte. Continua valendo que a sede do MASAF (Roma) NUNCA e FACT_LOCATION.",
    EVIDENCE_CLASS: "OFFICIAL_ORGANIZATION_REGISTRY", SOURCE_ROLE: "DISCOVERY_IDENTITY",
    LEI: "REGISTRY != FIELD_SIGNAL — esta fonte nunca prova nada de campo",
    AUTOMATION_FEASIBILITY: "MEDIUM",
    NEGATIVE_CONTROL: { descricao: "planilha sem a coluna CODICE IT", esperado: "FAILED" }
  },

  "IT-T3-011": {
    OWNER_ID: "IT-OWN-AGRIOS", OWNER: "AGRIOS — Alto Adige", TERRITORY: "T3", VALUE: "P1",
    CANONICAL_ENTRY_URL: "https://www.agrios.it/it/per-i-frutticoltori/documenti-e-disciplinari/",
    aviso_de_idioma: "o site e primariamente em ALEMAO. A versao italiana vive em /it/. Detector que so procura palavras italianas na home NAO acha nada — foi o que gerou o falso diagnostico de 'JavaScript'.",
    DISCOVERY_METHOD: "pagina de documentos lista os PDFs e planilhas",
    RETRIEVAL_METHOD: "GET no PDF", ROUTE_TYPE: "DISCOVERED_ROUTE",
    ACCESS_INSTRUMENT: "HTTP", AUTH_REQUIRED: false, BROWSER_REQUIRED: false, JS_REQUIRED: false,
    OUTPUT_TYPE: "PDF", EXPECTED_MIME: /^application\/pdf/, EXPECTED_SIGNATURE: "%PDF", MIN_BYTES: 1000000,
    IDENTITY_KEYS: ["ano_da_edicao"], DOCUMENT_ID_RULE: "AGRIOS:DIRETTIVE:{ANO}",
    DOCUMENT_DATE_FIELD: "o ano no titulo da capa", VERSION_FIELD: "ano da edicao",
    EXPECTED_CONTENT_MARKERS: ["DIRETTIVE PER", "FRUTTICOLTURA INTEGRATA"],
    DECLARED_FREQUENCY: "anual, pelo proprio titulo", OBSERVED_FREQUENCY: "NÃO SEI — uma edicao observada",
    UPDATE_BEHAVIOR: "ANUAL — nome de arquivo livre, muda a cada ano",
    HISTORICAL_OR_FORWARD: "NÃO SEI", ARCHIVE_REQUIREMENT: "NORMAL",
    EXPECTED_FAILURES: ["nome de arquivo fixado quebra no ano seguinte"],
    FAIL_CLOSED_RULE: "sem os marcadores de titulo = FAILED",
    FALLBACK: "a versao alema do mesmo documento",
    SOURCE_LOCATION_RULE: "Terlano (BZ)", FACT_LOCATION_RULE: "Alto Adige — area de aplicacao",
    EVIDENCE_CLASS: "TECHNICAL_GUIDELINE",
    LEI: "TECHNICAL_GUIDELINE != CURRENT_FIELD_SIGNAL e != DEROGA. Se aparecer uma deroga, ela e OUTRO documento e provavelmente OUTRO canal.",
    AUTOMATION_FEASIBILITY: "MEDIUM",
    NEGATIVE_CONTROL: { descricao: "PDF de outro documento do mesmo site", esperado: "FAILED por marcador de titulo ausente" }
  },

  "IT-T5-002": {
    OWNER_ID: "IT-OWN-014", OWNER: "Fondazione Edmund Mach — OpenPub (IRIS/CINECA)",
    TERRITORY: "T5", VALUE: "P1",
    CANONICAL_ENTRY_URL: "https://openpub.fmach.it/handle/{HANDLE}",
    OLD_ROUTE: "publications.fmach.it — host inexistente", CURRENT_ROUTE: "openpub.fmach.it",
    DISCOVERY_METHOD: "busca simples na interface; a rota de busca com parametros proprios devolveu HTTP 400 — usar as rotas que a interface gera",
    RETRIEVAL_METHOD: "GET na pagina do handle", ROUTE_TYPE: "APPLICATION_ROUTE",
    ACCESS_INSTRUMENT: "HTTP", AUTH_REQUIRED: false, BROWSER_REQUIRED: false, JS_REQUIRED: false,
    OUTPUT_TYPE: "HTML", EXPECTED_MIME: /^text\/html/, EXPECTED_SIGNATURE: "<", MIN_BYTES: 20000,
    IDENTITY_KEYS: ["handle"], DOCUMENT_ID_RULE: "FEM:HANDLE:{10449/NNNNN}",
    CAMPOS: ["PUBLICATION_ID", "TITLE", "AUTHOR_IDS", "DATE", "DOI", "SUBJECT/QUERY", "ABSTRACT"],
    LEI_CRITICA: "QUERY_MATCH != PROVED_TOPIC. Os 188 resultados da busca por 'Drosophila suzukii' sao 188 REGISTROS QUE A BUSCA CASOU — nao 188 evidencias independentes, nao 188 pesquisadores, e nao 188 trabalhos comprovadamente sobre o tema. A contagem e da busca, nao do assunto.",
    DECLARED_FREQUENCY: "nenhuma", OBSERVED_FREQUENCY: "IRREGULAR — repositorio alimentado quando sai publicacao",
    UPDATE_BEHAVIOR: "ADITIVO", HISTORICAL_OR_FORWARD: "HISTORICAL", ARCHIVE_REQUIREMENT: "BAIXO",
    EXPECTED_FAILURES: ["busca com parametros proprios devolve HTTP 400", "resultado vazio = FAILED, nao 'nenhuma publicacao'"],
    FAIL_CLOSED_RULE: "lista de busca vazia e FAILED",
    FALLBACK: "navegar por Settore Scientifico Disciplinare",
    SOURCE_LOCATION_RULE: "San Michele all'Adige (TN)",
    FACT_LOCATION_RULE: "UNKNOWN por padrao — so preencher se o proprio trabalho declarar a area de estudo",
    EVIDENCE_CLASS: "SCIENTIFIC_EVIDENCE", AUTOMATION_FEASIBILITY: "MEDIUM",
    NEGATIVE_CONTROL: { descricao: "busca que retorna zero resultados", esperado: "FAILED, nunca 'zero publicacoes sobre o tema'" }
  },

  "IT-T9-008": {
    OWNER_ID: "IT-OWN-ADAMA-IT", OWNER: "ADAMA Italia", TERRITORY: "T9", VALUE: "P2",
    CANONICAL_ENTRY_URL: "https://www.adama.com/italia/it/articoli-news-ed-eventi-main",
    DISCOVERY_METHOD: "listagem de artigos no site", RETRIEVAL_METHOD: "navegador com janela",
    ROUTE_TYPE: "BROWSER_DISCOVERED_ROUTE",
    ACCESS_INSTRUMENT: "BROWSER", AUTH_REQUIRED: false, BROWSER_REQUIRED: true, JS_REQUIRED: "NÃO SEI — o servidor recusa antes de dar para testar",
    WAF_OBSERVED: true,
    OUTPUT_TYPE: "BROWSER_RENDERED_EXTRACT",
    LEI_CRITICA: "SERVER_RAW > BROWSER_RENDERED_DOCUMENT > BROWSER_RENDERED_EXTRACT. Hoje so temos o terceiro. NAO existe caminho honesto para virar RAW_PRESERVED enquanto o servidor recusar cliente sem navegador. Nao forcar.",
    IDENTITY_KEYS: ["canonical_url", "article_published_time"],
    DOCUMENT_ID_RULE: "ADAMA:{CANONICAL_URL}:{PUBLISHED_TIME}",
    DOCUMENT_DATE_FIELD: "meta article:published_time e article:modified_time (o site e Drupal 10 e expoe os dois)",
    VERSION_FIELD: "modified_time",
    DECLARED_FREQUENCY: "nenhuma", OBSERVED_FREQUENCY: "NÃO SEI",
    UPDATE_BEHAVIOR: "ADITIVO", HISTORICAL_OR_FORWARD: "HISTORICAL", ARCHIVE_REQUIREMENT: "NORMAL",
    EXPECTED_FAILURES: ["403 se tentar sem navegador — e o comportamento NORMAL, nao uma queda da fonte"],
    FAIL_CLOSED_RULE: "extrato sem canonical_url ou sem published_time nao tem identidade — FAILED",
    FALLBACK: "nenhum",
    SOURCE_LOCATION_RULE: "site nacional",
    FACT_LOCATION_RULE: "UNKNOWN — artigo de empresa nao localiza fato de campo. NUNCA inferir pela sede.",
    EVIDENCE_CLASS: "COMPANY_CLAIM", LEI: "COMPANY_CLAIM != REGULATORY_FACT — vale inclusive para a ADAMA",
    AUTOMATION_FEASIBILITY: "MEDIUM — exige navegador. BROWSER_REQUIRED != SOURCE_UNAUTOMATABLE.",
    NEGATIVE_CONTROL: { descricao: "extrato sem published_time", esperado: "FAILED por falta de identidade" }
  }
};

export const CONTRACT_IDS = Object.keys(CONTRACTS);
